// Archivo generado automáticamente desde pokemon.xlsx (hoja 'Hoja 2')
const POKEMON = [
  {id: 1, name: "Flutide", types: ["Planta"], image: "Sprite/Flutide.png", definition: "Planta colgante", dex_draft: `Flutide pasa gran parte de su vida suspendido de ramas bajas y arbustos, balanceándose suavemente con el viento. Sus tejidos son extremadamente sensibles a las variaciones de gravedad y movimiento, permitiéndole detectar la presencia de otros seres vivos antes de que entren en su campo visual. Cuando percibe peligro, permanece inmóvil simulando ser una flor corriente.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 1 }, evolutionLine: [1, 2, 3]},
  {id: 2, name: "Pendulora", types: ["Planta", "Psíquico"], image: "Sprite/Pendulora.png", definition: "Planta colgante", dex_draft: `La percepción de Pendulora se extiende mucho más allá de sus sentidos físicos. Utiliza el balanceo constante de su cuerpo para interpretar vibraciones del entorno, corrientes de aire y pequeños cambios en la posición de los objetos cercanos. Es habitual encontrar varios individuos colgando juntos en silencio, sincronizando sus movimientos como si compartieran información invisible.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 1 }, evolutionLine: [1, 2, 3]},
  {id: 3, name: "Inverfucsia", types: ["Planta", "Psíquico"], image: "Sprite/Inverfucsia.png", definition: "Planta colgante", dex_draft: `Inverfucsia observa el mundo desde una perspectiva completamente distinta a la mayoría de las especies. Sus órganos sensoriales interpretan el movimiento y el equilibrio con una precisión extraordinaria, permitiéndole anticipar trayectorias y cambios en su entorno antes de que ocurran. En bosques tranquilos puede verse suspendida durante horas sin moverse, oscilando apenas unos milímetros mientras analiza todo lo que sucede a su alrededor.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 1 }, evolutionLine: [1, 2, 3]},
  {id: 4, name: "Brasquill", types: ["Fuego"], image: "Sprite/Brasquill.png", definition: "Glotón brasa", curiosidades: "Su respiración puede producir leves chispas al bostezar.", dex_draft: `Brasquill pasa la mayor parte del día explorando su territorio en silencio. Aunque parece tranquilo, su cuerpo almacena una enorme cantidad de calor interno que se libera cuando se emociona o se siente amenazado. 
Su denso pelaje negro actúa como aislante térmico, permitiéndole conservar energía durante largos periodos. Las franjas claras de su cabeza funcionan como reguladores de temperatura y cambian ligeramente de tonalidad cuando se excita.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [4, 5, 6]},
  {id: 5, name: "Incinerauge", types: ["Fuego", "Siniestro"], image: "Sprite/Incinerauge.png", definition: "Glotón Ígneo", dex_draft: `Incinerauge vive guiado por sus impulsos. Recorre grandes distancias persiguiendo olores, sonidos o movimientos que despierten su curiosidad. Su aliento caliente puede encender la vegetación seca sin que llegue a darse cuenta. Las cámaras térmicas de su pecho han crecido considerablemente. El aire que exhala sale a temperaturas muy elevadas, generando pequeñas llamaradas involuntarias cuando está alterado o emocionado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [4, 5, 6]},
  {id: 6, name: "Ragestrail", types: ["Fuego", "Siniestro"], image: "Sprite/Ragestrail.png", definition: "Glotón Ígneo", dex_draft: `Ragestrail representa la pasión llevada al límite. Aunque normalmente permanece inmóvil y observador, cuando algo despierta su instinto es capaz de perseguirlo durante días enteros sin detenerse.
Su sistema respiratorio funciona como un enorme horno biológico. En lugar de expulsar grandes llamaradas, libera un constante aliento incandescente que calienta el aire a su alrededor. Su musculatura está diseñada para explosiones repentinas de velocidad y fuerza.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [4, 5, 6]},
  {id: 7, name: "Fluwel", types: ["Agua"], image: "Sprite/Fluwel.png", definition: "Puño de Agua", dex_draft: `Fluwel es juguetón y valiente. Le encanta golpear el agua con sus pequeñas patas, creando ondas que usa para medir su fuerza. Cuando se concentra, el agua responde a sus movimientos como si bailara con él.
Aunque es curioso y algo cabezota, nunca huye de un desafío. Su cuerpo es ligero y flexible, y aprende rápido a moverse siguiendo el ritmo de las corrientes.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [7, 8, 9]},
  {id: 8, name: "Ottrine", types: ["Agua", "Lucha"], image: "Sprite/Ottrine.png", definition: "Luchador de las Corrientes", dex_draft: `Ottrine se entrena en las orillas de los ríos, enfrentando el flujo del agua para fortalecer su cuerpo. Usa sus brazos y cola como remos, y sus movimientos son tan precisos que apenas levantan espuma.
Su expresión seria no engaña: es un Pokémon disciplinado que dedica cada día a perfeccionar su técnica. Cuando pelea, combina golpes rápidos con fluidos movimientos acuáticos que desconciertan al rival.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [7, 8, 9]},
  {id: 9, name: "Marinoir", types: ["Agua", "Lucha"], image: "Sprite/Marinoir.png", definition: "Guerrero del Mar", dex_draft: `Marinoir domina la fuerza y el equilibrio del agua con absoluta maestría. Cada uno de sus movimientos está en armonía con la marea, capaz de desatar torrentes con un simple golpe.
Es un Pokémon noble y protector, que solo combate cuando es necesario. Se dice que puede desviar una ola entera con el impulso de sus brazos, y que su entrenamiento bajo cascadas dura días enteros sin descanso.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [7, 8, 9]},
  {id: 10, name: "Brilluga", types: ["Bicho"], image: "Sprite/Brilluga.png", definition: "Larva de Luz", dex_draft: `Brilluga habita bajo la corteza de los árboles húmedos del Bosque Brumoria. Su cuerpo translúcido emite un resplandor tenue que usa para ahuyentar depredadores. Cuando varias se agrupan, sus luces se sincronizan formando un parpadeo rítmico que parece imitar el pulso del bosque. Los investigadores creen que esta especie regula la bioluminiscencia según las fases lunares.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [10, 11, 12]},
  {id: 11, name: "Crisvolt", types: ["Bicho", "Eléctrico"], image: "Sprite/Crisvolt.png", definition: "Pupa Chispeante", dex_draft: `Durante su metamorfosis, Crisvolt se encierra en un capullo cristalino que acumula energía estática. Las descargas internas hacen vibrar el aire y generan un zumbido apenas audible que anuncia una tormenta próxima. En noches muy húmedas, su capullo brilla con luz azulada y actúa como faro para otras criaturas del bosque.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [10, 11, 12]},
  {id: 12, name: "Voltasmoth", types: ["Bicho", "Eléctrico"], image: "Sprite/Voltasmoth.png", definition: "Luciérnaga Nocturna", dex_draft: `Voltasmoth ilumina los claros del bosque con el destello de sus alas. Su vuelo crea patrones eléctricos que sirven de lenguaje entre individuos. Cuando una tormenta se aproxima, su cuerpo resplandece con fuerza y se dice que el cielo responde a su danza con relámpagos lejanos. Los antiguos Aionitas la consideraban un símbolo de guía y conocimiento.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [10, 11, 12]},
  {id: 13, name: "Claynip", types: ["Bicho"], image: "Sprite/Claynip.png", definition: "Larva Terrera", dex_draft: `Claynip excava túneles en la tierra húmeda, reforzándolos con arcilla que amasa con sus propias secreciones. Vive en pequeñas colonias bajo las raíces, donde comparte calor con sus compañeras. Es común verlas competir por el mismo alimento que las larvas de Brilluga, aunque ambas especies rara vez se cruzan al mismo tiempo del día.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [13, 14, 15]},
  {id: 14, name: "Pupterra", types: ["Bicho", "Tierra"], image: "Sprite/Pupterra.png", definition: "Capullo de Arcilla", dex_draft: `Pupterra se sella en una cámara de barro endurecido que construye ella misma. El calor del sol solidifica su envoltura, y los crujidos que emite al secarse indican el avance de su metamorfosis. Sus capullos endurecidos refuerzan el suelo y ayudan a prevenir la erosión en zonas inestables.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [13, 14, 15]},
  {id: 15, name: "Terraphex", types: ["Bicho", "Tierra"], image: "Sprite/Terraphex.png", definition: "Arquitecta del Suelo", dex_draft: `Terraphex levanta nidos de barro perfectamente estructurados, donde almacena alimento y protege a su prole. Cada panal tiene una forma distinta según la composición del terreno. Sus alas levantan un polvo fino que endurece la tierra al contacto, y se dice que los antiguos Aionitas imitaban sus colmenas al construir sus templos subterráneos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [13, 14, 15]},
  {id: 16, name: "Mossnip", types: ["Planta"], image: "Sprite/Mossnip.png", definition: "Conejo de Musgo", dex_draft: `Mossnip vive en los claros húmedos del Bosque, donde el sol apenas llega entre los árboles. Su pelaje, cubierto de musgo y pequeñas hojas, absorbe la humedad del aire y mantiene fresco el suelo donde descansa. Cuando se siente amenazado, se agacha y se inmoviliza, pareciendo un simple montículo verde. Su presencia indica un bosque sano y equilibrado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [16, 17]},
  {id: 17, name: "Thorabbit", types: ["Planta"], image: "Sprite/Thorabbit.png", definition: "Guardián del Bosque", dex_draft: `Thorabbit canaliza la energía vital del bosque a través del manto vegetal que cubre su cuerpo. Sus orejas largas, con nervaduras semejantes a hojas, captan los cambios de humedad y temperatura, permitiéndole anticipar tormentas. Donde salta, la hierba brota momentáneamente a su paso. Los antiguos Aionitas lo consideraban un espíritu protector de los claros sagrados, símbolo de fertilidad y renovación.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [16, 17]},
  {id: 18, name: "Solfinch", types: ["Volador", "Hada"], image: "Sprite/Solfinch.png", definition: "Pájaro Solar", dex_draft: `Solfinch despierta con el primer rayo de luz, extendiendo sus alas para absorber el calor del sol. Cuando canta, las gotas de rocío a su alrededor comienzan a brillar como diminutos soles. Es un Pokémon alegre y sociable que armoniza los ritmos del bosque al amanecer, marcando el inicio de cada nuevo día.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [18, 19, 20]},
  {id: 19, name: "Aurelark", types: ["Volador", "Hada"], image: "Sprite/Aurelark.png", definition: "Pájaro del Alba", dex_draft: `Cuando el bosque comienza a calentar, Aurelark se eleva en espirales doradas, dispersando motas luminosas que nutren a los insectos y favorecen la floración. Sus alas vibran con tal velocidad que el aire a su alrededor se ondula, dejando un halo de luz suspendido. Representa la energía vital que enlaza a todos los seres con el amanecer.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [18, 19, 20]},
  {id: 20, name: "Dawnazar", types: ["Volador", "Hada"], image: "Sprite/Dawnazar.png", definition: "Guardián del Amanecer", dex_draft: `Cuando los cielos de Aionia se tiñen de rosa, Dawnazar extiende sus alas y el bosque se inunda de luz. Cada pluma refleja los tonos del alba, y su canto disipa la niebla y ahuyenta la oscuridad. Donde vuela, renace la esperanza; su presencia anuncia el comienzo de un nuevo ciclo de vida.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [18, 19, 20]},
  {id: 21, name: "Noctavi", types: ["Volador", "Fantasma"], image: "Sprite/Noctavi.png", definition: "Pájaro Crepuscular", dex_draft: `"Noctavi aparece cuando el bosque se sumerge en penumbra. Su llama etérea no quema ni ilumina: marca el límite entre la vigilia y el sueño. A menudo acompaña a los viajeros solitarios, flotando en silencio hasta el amanecer. Muchos lo confunden con un espíritu benigno, pero en realidad es un ave tímida que teme el ruido y la luz intensa. Su cresta espectral reacciona a las emociones humanas, y los antiguos Aionitas lo consideraban mensajero del alma dormida."`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [21, 22, 23]},
  {id: 22, name: "Phaswift", types: ["Volador", "Fantasma"], image: "Sprite/Phaswift.png", definition: "Pájaro de Penumbra", dex_draft: `"Phaswift se entrena volando entre las corrientes de niebla. Su llama se intensifica cuando percibe energía vital cerca, lo que le permite detectar presencias invisibles. Dicen que si revolotea sobre un claro, significa que la bruma está viva y el bosque observa. Es un Pokémon curioso y silencioso, guía de otros nocturnos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [21, 22, 23]},
  {id: 23, name: "Umbraciel", types: ["Volador", "Fantasma"], image: "Sprite/Umbraciel.png", definition: "Guardián Espectral", dex_draft: `"Umbraciel reina sobre los cielos oscuros de Aionia. Su fuego frío atraviesa la niebla, iluminando solo aquello que desea mostrar. Protege el equilibrio entre la noche y el amanecer, y se dice que cuando su canto resuena, incluso los ecos del tiempo se detienen por respeto. Los textos Aionitas lo describen como el heraldo de Noxal, y se cree que sus alas pueden romper los límites entre los sueños y la realidad."`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [21, 22, 23]},
  {id: 24, name: "Topin", types: ["Normal"], image: "Sprite/Topin.png", definition: "Pokémon Topo Curioso", dex_draft: `Topin habita praderas, caminos rurales y zonas cercanas a asentamientos humanos. Pasa la mayor parte del día excavando túneles poco profundos en busca de raíces y pequeños invertebrados. Su hocico blando y sensible le permite detectar vibraciones en el suelo, avisándole de peligros cercanos. Es un Pokémon dócil y confiado, por lo que suele ser uno de los primeros en acercarse a entrenadores principiantes. Sus madrigueras airean la tierra y mejoran la calidad del suelo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [24, 25]},
  {id: 25, name: "Topador", types: ["Normal"], image: "Sprite/Topador.png", definition: "Pokémon Excavador", dex_draft: `Al evolucionar, Topador desarrolla un cuerpo más robusto y garras resistentes adaptadas a excavar terrenos compactos. Sus largos bigotes actúan como sensores, permitiéndole orientarse incluso en completa oscuridad. Aunque sigue siendo pacífico, defiende con firmeza su territorio si se siente acorralado. Suele crear extensas redes de túneles utilizadas por otros Pokémon pequeños. Es muy apreciado en zonas agrícolas, ya que remueve la tierra y facilita el crecimiento de las plantas.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [24, 25]},
  {id: 26, name: "Magmorok", types: ["Roca", "Fuego"], image: "Sprite/Magmorok.png", definition: "Fragmento Ígneo", curiosidades: "Cuando su temperatura interna desciende demasiado, busca grietas volcánicas para “alimentar” su fuego interno con calor y minerales fundidos.", dex_draft: `Magmarock es una roca viva nacida del magma aún joven de la Tierra. Su cuerpo está formado por una costra pétrea incompleta que apenas logra contener el calor de su interior. El magma líquido aflora constantemente entre sus grietas, iluminando su cuerpo con destellos anaranjados.

Se desplaza utilizando sus fuertes brazos para arrastrarse por terrenos volcánicos, donde deja pequeñas marcas quemadas sobre la roca. Aunque su aspecto parece frágil, su núcleo ardiente puede mantenerse activo durante siglos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [26, 27, 28]},
  {id: 27, name: "Magmorus", types: ["Roca", "Fuego"], image: "Sprite/Magmorus.png", definition: "Núcleo Fundente", dex_draft: `Con la madurez, Magmorus desarrolla nuevas capas de roca volcánica alrededor de su cuerpo, creando una armadura natural capaz de soportar enormes presiones y temperaturas. Bajo esa coraza, el magma circula lentamente por una red de canales internos que recuerdan al sistema circulatorio de otros seres vivos.

Cuando se siente amenazado, libera gases acumulados en su interior a través de las grietas de su cuerpo, provocando pequeñas detonaciones y nubes de vapor abrasador.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [26, 27, 28]},
  {id: 28, name: "Magmolith", types: ["Roca", "Fuego"], image: "Sprite/Magmolith.png", definition: "Coloso Basáltico", dex_draft: `Magmoliz representa el estado más estable de esta antigua línea evolutiva. Su cuerpo está compuesto por gruesas placas de basalto endurecido que contienen un inmenso reservorio de magma en constante movimiento.

A diferencia de sus preevoluciones, apenas pierde calor al exterior, conservando casi toda su energía bajo su coraza. Se desplaza lentamente por regiones volcánicas y montañosas, donde su presencia modifica el paisaje con el paso de los años. Solo muestra agresividad cuando percibe alteraciones que amenazan el equilibrio geológico de su territorio.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [26, 27, 28]},
  {id: 29, name: "Garrisk", types: ["Volador"], image: "Sprite/Garrisk.png", definition: "Pokémon Merodeador Costero", dex_draft: `Garrisk habita playas rocosas, puertos abandonados y restos de naufragios recientes. Es extremadamente observador y paciente, permaneciendo inmóvil durante horas mientras vigila el horizonte en busca de actividad. Se alimenta de restos orgánicos arrastrados por las mareas y pequeños Pokémon debilitados. Aunque puede volar largas distancias, prefiere desplazarse a pie por la arena, usando su pico largo para rebuscar entre escombros y algas. Suele seguir a embarcaciones desde lejos, anticipando oportunidades.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [29, 30]},
  {id: 30, name: "Corvanta", types: ["Volador", "Siniestro"], image: "Sprite/Corvanta.png", definition: "Pokémon Carroñero de Naufragios", dex_draft: `Corvanta es un ave dominante de las costas peligrosas, donde abundan los restos de barcos hundidos. Su inteligencia y agresividad le permiten expulsar a otros carroñeros y reclamar zonas ricas en recursos. Aprovecha tormentas y mareas fuertes para localizar nuevos naufragios, guiándose por corrientes de aire y olores metálicos. Aunque rara vez ataca sin motivo, no duda en intimidar con despliegues de alas y graznidos ásperos. La presencia de Corvanta indica aguas traicioneras y actividad reciente en la costa.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [29, 30]},
  {id: 33, name: "Eeveon", types: ["Normal"], image: "Sprite/Eeveon.png", definition: "Pokémon Primigenio", curiosidades: "Cuando Eeveon fue descubierto y se confirmó su parentesco con Eevee, numerosos investigadores intentaron provocar una evolución utilizando distintas fuentes de energía elemental y métodos conocidos de evolución. Ninguno produjo efecto alguno. Este hallazgo reforzó la teoría de que la extraordinaria capacidad evolutiva de Eevee apareció más tarde en la historia de su linaje y no estaba presente en su ancestro primigenio.", dex_draft: `Eeveon es el ancestro salvaje de Eevee, una criatura de instinto agudo y reflejos felinos que habitaba bosques densos y praderas abiertas mucho antes de que aparecieran las formas modernas de su linaje.

Su pelaje espeso y su estructura corporal más robusta lo protegían del clima y de los depredadores, mientras que su ADN, completamente estable, carecía aún de la plasticidad genética que caracteriza a Eevee.

A diferencia de sus descendientes, Eeveon apenas mostraba variaciones adaptativas influenciadas por el entorno. Se considera el punto de origen del linaje evolutivo más versátil conocido.`, stats: { hp: 60, atk: 70, def: 55, spa: 45, spd: 50, spe: 70, total: 350 }, evolutionLine: [33]},
  {id: 37, name: "Algoryn", types: ["Agua", "Planta"], image: "Sprite/Algoryn.png", definition: "Pokémon Serpiente de Algas", dex_draft: `Algoryn habita lagunas costeras, praderas submarinas y zonas donde las algas crecen en abundancia. Su cuerpo flexible está cubierto por hojas vivas que brotan de su piel y se regeneran constantemente gracias a la luz solar. Estas algas le permiten camuflarse entre la vegetación marina y producir oxígeno incluso en aguas pobres. Se desplaza lentamente, dejándose llevar por las corrientes, y rara vez ataca, prefiriendo huir y confundirse con el entorno. Su presencia favorece la salud del ecosistema acuático.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [37]},
  {id: 38, name: "Flamutt", types: ["Fuego"], image: "Sprite/Flamutt.png", definition: "Cachorro Ígneo", dex_draft: `Flamutt almacena calor en la pequeña llama que arde sobre su cabeza y en la brasa de su cola. Es frecuente verlo explorando zonas cálidas y soleadas, donde juega persiguiendo insectos y pequeñas corrientes de aire caliente. Su naturaleza curiosa le lleva a aventurarse lejos de la manada más de lo recomendable.`, stats: { hp: 50, atk: 65, def: 45, spa: 60, spd: 50, spe: 80, total: 350 }, evolutionLine: [38, 39]},
  {id: 39, name: "Flarehound", types: ["Fuego"], image: "Sprite/Flarehound.png", definition: "Sabueso Ardiente", dex_draft: `Al crecer lejos de las regiones volcánicas, Flamutt desarrolla un pelaje ligero y una combustión más eficiente. Flarehound es capaz de recorrer grandes distancias sin agotarse, dejando breves destellos de fuego a su paso. Los incendios provocados por sus carreras suelen ser débiles y forman parte del ciclo natural de los ecosistemas donde habita.`, stats: { hp: 80, atk: 110, def: 75, spa: 90, spd: 70, spe: 85, total: 510 }, evolutionLine: [38, 39]},
  {id: 40, name: "Volkrag", types: ["Fuego", "Roca"], image: "Sprite/Volkrag.png", definition: "Lobo Volcánico", dex_draft: `Los ejemplares que habitan las laderas volcánicas incorporan minerales y cenizas a su pelaje durante el crecimiento. Con el tiempo, estos materiales se endurecen formando una coraza rocosa atravesada por magma incandescente. Volkrag protege ferozmente las entradas de las grutas volcánicas y rara vez abandona su territorio.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [40]},
  {id: 41, name: "Duneek", types: ["Tierra"], image: "Sprite/Duneek.png", definition: "Zorro de arena", curiosidades: "Los antiguos viajeros lo llamaban “el eco del desierto”, porque podían escuchar sus pasos pero nunca verlo.", dex_draft: `Duneek vive oculto durante el día, enterrado bajo la arena caliente, y sale solo cuando cae la noche.
Sus grandes orejas detectan las vibraciones de los insectos bajo el suelo, permitiéndole cazar sin emitir un solo sonido.
Su pelaje claro refleja el sol y su nariz puede filtrar el aire cargado de polvo, lo que le permite sobrevivir en los desiertos más hostiles.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [41, 42]},
  {id: 42, name: "Noctennec", types: ["Tierra", "Siniestro"], image: "Sprite/Noctennec.png", definition: "Zorro nocturno", dex_draft: `La evolución de Duneek ocurre cuando perfecciona su dominio de la oscuridad y el silencio.
Noctennec se mueve como una sombra entre las dunas, dejando huellas que el viento borra al instante.
Sus ojos reflejan la luz de la luna con un brillo dorado, y se dice que puede confundir a sus presas proyectando ilusiones con su propio movimiento.
Caza solo, y los que han visto su silueta aseguran que no emite sonido alguno ni siquiera al respirar.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [41, 42]},
  {id: 53, name: "Dropletle", types: ["Bicho"], image: "Sprite/Dropletle.png", definition: "Escarabajo del Rocío", dex_draft: `Dropletle vive enterrado bajo la arena, dejando al descubierto solo el caparazón de su espalda, que brilla con diminutas gotas de agua condensada.
Durante la noche extiende sus alas para atrapar la humedad del aire frío, formando pequeñas perlas que almacena para hidratarse durante el día.
Se le considera un símbolo de esperanza en los desiertos más áridos, pues allí donde habita, las plantas parecen resistir mejor el calor.`, stats: { hp: 55, atk: 45, def: 70, spa: 35, spd: 75, spe: 40, total: 320 }, evolutionLine: [53, 54]},
  {id: 54, name: "Hydrabeet", types: ["Bicho", "Agua"], image: "Sprite/Hydrabeet.png", definition: "Escarabajo del Vapor", dex_draft: `Hydrabeet ha desarrollado un sistema natural que convierte la humedad que almacena en vapor caliente, el cual libera por sus élitros para crear una neblina protectora.
En las madrugadas del desierto, su presencia cubre las dunas con un manto brillante que se asemeja a la niebla marina.
Su caparazón oscuro absorbe el calor del sol, y su cuerpo regula la presión interna para liberar chorros de vapor a modo de defensa o comunicación.`, stats: { hp: 80, atk: 65, def: 85, spa: 90, spd: 95, spe: 75, total: 490 }, evolutionLine: [53, 54]},
  {id: 55, name: "Shellin", types: ["Agua"], image: "Sprite/Shellin.png", definition: "Pokémon Caracol Marino", dex_draft: `Este Pokémon vive adherido a rocas costeras y utiliza su pequeño caparazón espiral para protegerse de las corrientes. Es lento y tímido, apenas puede disparar un chorrito de agua desde la punta de su concha. Su cuerpo gelatinoso le permite ocultarse en grietas húmedas cuando percibe peligro.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [55, 56, 57]},
  {id: 56, name: "Shellump", types: ["Agua"], image: "Sprite/Shellump.png", definition: "Pokémon Propulsor", dex_draft: `Su cuerpo se ha fortalecido y su caparazón ha comenzado a endurecerse. Puede expulsar chorros de agua a presión desde la parte superior para impulsarse bajo el mar. Vive en zonas de corrientes fuertes y compite con sus congéneres golpeando sus caparazones. Pequeñas lapas y verdín crecen sobre él, señal de su madurez.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [55, 56, 57]},
  {id: 57, name: "Sheelljet", types: ["Agua"], image: "Sprite/Sheelljet.png", definition: "Pokémon Turbina", dex_draft: `Un Pokémon poderoso que domina la presión del agua para defenderse y desplazarse. Su caparazón masivo actúa como una turbina natural: lanza chorros capaces de moverlo a gran velocidad o perforar rocas blandas. Se dice que cuando un Sheelljet se enfada, el sonido de su géiser puede oírse a kilómetros.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [55, 56, 57]},
  {id: 58, name: "Murmurel", types: ["Hada", "Siniestro"], image: "Sprite/Murmurel.png", definition: "Pokémon Augurio", curiosidades: "Muchos exploradores afirman haber sentido una presencia observándolos durante la noche. A la mañana siguiente suelen descubrir pequeñas huellas de Murmurel alrededor de su campamento.", dex_draft: `Recorre los bosques y humedales de Aionia durante la noche utilizando su dedo sensorial para detectar rastros emocionales en el entorno. Aunque su apariencia inquietante ha dado origen a numerosas supersticiones, suele acercarse a los Pokémon perdidos o asustados y permanecer cerca de ellos hasta que recuperan la calma.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [58]},
  {id: 59, name: "Vigilion", types: ["Psíquico"], image: "Sprite/Vigilion.png", definition: "Pokémon Observador", curiosidades: "Las marcas que cubren su enorme pico cambian lentamente con los años. Ningún investigador ha conseguido descifrar su significado, aunque cada ejemplar presenta un patrón completamente único.", dex_draft: `Permanece inmóvil durante horas en las marismas y turberas de Aionia observando la superficie del agua. Sus sentidos son tan precisos que puede detectar vibraciones imperceptibles para otros Pokémon, lo que ha dado origen a leyendas que le atribuyen la capacidad de ver acontecimientos futuros.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [59]},
  {id: 60, name: "Chillik", types: ["Normal", "Siniestro"], image: "Sprite/Chillik.png", definition: "Pokémon Alborotador", dex_draft: `Chillik vive en grupos pequeños cerca de selvas costeras y ruinas naturales. Aunque su tamaño es reducido, posee un aparato vocal desproporcionadamente desarrollado, capaz de emitir chillidos agudos que desorientan a otros Pokémon. Utiliza estos gritos para ahuyentar depredadores y reclamar territorio sin recurrir al combate físico. Su comportamiento es caótico e impredecible, y aprende rápidamente qué sonidos provocan miedo o incomodidad en cada especie que encuentra.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [60, 61, 62]},
  {id: 61, name: "Gorvok", types: ["Normal", "Siniestro"], image: "Sprite/Gorvok.png", definition: "Pokémon Vociferante", dex_draft: `Al evolucionar, Gorvok adquiere mayor control sobre su voz y una estructura torácica que amplifica las vibraciones sonoras. Sus gritos pueden resonar a grandes distancias, provocando pánico en Pokémon más pequeños y desorganizando grupos enteros. Es territorial y provocador, usando demostraciones sonoras constantes para imponer su presencia. Aunque rara vez inicia ataques físicos, su capacidad para desgastar psicológicamente a sus oponentes lo convierte en un adversario temido.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [60, 61, 62]},
  {id: 62, name: "Ulvarroar", types: ["Normal", "Siniestro"], image: "Sprite/Ulvarroar.png", definition: "Pokémon Cañón Sonoro", dex_draft: `Ulvarroar es la fase adulta y más peligrosa de esta especie. Su garganta y cavidad bucal funcionan como un auténtico cañón de sonido, capaz de liberar ondas vocales concentradas que sacuden el aire y el suelo. Estos estallidos pueden derribar enemigos antes de que se acerquen. Extremadamente dominante, controla amplias zonas mediante intimidación acústica constante. Se dice que su rugido puede oírse incluso durante tormentas, marcando el territorio de forma inequívoca.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [60, 61, 62]},
  {id: 63, name: "Corlin", types: ["Agua"], image: "Sprite/Corlin.png", definition: "Pokémon Brote Coralino", dex_draft: `Corlín habita aguas costeras poco profundas donde la luz solar favorece el crecimiento de coral. Los pequeños apéndices de su cabeza son colonias coralinas vivas que se desarrollan en simbiosis con su cuerpo, obteniendo nutrientes de su piel húmeda. A cambio, el coral le proporciona camuflaje y absorbe toxinas del agua. Es un Pokémon dócil y curioso, que suele seguir a bancos de peces pequeños mientras explora el fondo marino.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [63, 64, 65]},
  {id: 64, name: "Coralyn", types: ["Agua"], image: "Sprite/Coralyn.png", definition: "Pokémon Coral Vivo", dex_draft: `A medida que Coralyn madura, el coral de su cabeza se ramifica y endurece, volviéndose más resistente a las corrientes fuertes. Este Pokémon migra hacia arrecifes más profundos, donde usa sus cuernos coralinos para anclarse y descansar sin ser arrastrado. Su piel secreta minerales que refuerzan las colonias coralinas, convirtiéndolo en un elemento clave para la regeneración de arrecifes dañados. Es pacífico, pero protege su territorio con firmeza.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [63, 64, 65]},
  {id: 65, name: "Arrecor", types: ["Agua"], image: "Sprite/Arrecor.png", definition: "Pokémon Guardián del Arrecife", dex_draft: `Arrecor es la forma final y más robusta de esta especie. Sus grandes cuernos coralinos albergan múltiples organismos marinos, formando un microecosistema móvil. Gracias a su gran masa y fuerza, estabiliza zonas del arrecife afectadas por tormentas o depredadores. Aunque su aspecto es imponente, rara vez ataca; prefiere intimidar y mantener el equilibrio natural de su entorno. La presencia de Arrecor es señal de un ecosistema marino sano y estable.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [63, 64, 65]},
  {id: 66, name: "Pebblid", types: ["Roca", "Agua"], image: "Sprite/Pebblid.png", definition: "Pokémon Piedra Mareal", dex_draft: `Pebblid habita las costas rocosas del oeste de Aionia, donde permanece inmóvil durante horas absorbiendo calor y minerales de las piedras húmedas. Las algas y pequeños organismos que crecen sobre su cuerpo le sirven como camuflaje frente a los depredadores.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [66, 67, 68]},
  {id: 67, name: "LittoRock", types: ["Roca", "Agua"], image: "Sprite/LittoRock.png", definition: "Pokémon Acantilado Viviente", dex_draft: `Al crecer, su cuerpo desarrolla cavidades capaces de retener agua marina incluso durante la marea baja. Numerosas criaturas costeras utilizan estas pequeñas reservas como refugio temporal, formando discretas comunidades a su alrededor.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [66, 67, 68]},
  {id: 68, name: "Thalagran", types: ["Roca", "Agua"], image: "Sprite/Thalagran.png", definition: "Pokémon Bastión Costero", dex_draft: `Con el paso de los años, su caparazón acumula sedimentos, algas y pequeños organismos marinos hasta convertirse en un ecosistema completo. Algunos ejemplares permanecen tanto tiempo inmóviles que llegan a confundirse con islotes costeros.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [66, 67, 68]},
  {id: 72, name: "Mazorik", types: ["Planta"], image: "Sprite/Mazorik.png", definition: "Pokémon Mazorca", curiosidades: "Se dice que las cosechas son más abundantes en los campos donde se esconde un Mazorik, aunque los agricultores raramente logran verlo.", dex_draft: `Mazorik habita en los campos fértiles donde crece el maíz silvestre. Su cuerpo redondeado, formado por granos dorados y hojas verdes envolventes, brilla al sol como una pequeña joya vegetal.
Es un Pokémon travieso que disfruta escondiéndose entre las plantas para lanzar semillas endurecidas a los intrusos. Sus movimientos rápidos entre los tallos hacen difícil atraparlo, y cuando se siente seguro, emite un leve crujido parecido al de las hojas secas al viento.
A medida que absorbe luz solar, sus granos se vuelven más brillantes, señal de que su energía está madurando para la evolución.`, stats: { hp: 55, atk: 65, def: 55, spa: 40, spd: 50, spe: 60, total: 325 }, evolutionLine: [72, 73]},
  {id: 73, name: "Corstalk", types: ["Planta"], image: "Sprite/Corstalk.png", definition: "Pokémon Espiga", curiosidades: "Algunos agricultores de Aionia consideran a Corstalk un espíritu protector de la tierra, y dejan pequeñas espigas doradas en los linderos de los campos en su honor.", dex_draft: `Corstalk es la evolución de Mazorik, una criatura ágil que combina la firmeza del tallo con la astucia del depredador vegetal. Su cuerpo está formado por hojas entrelazadas que se afilan con el viento, y en su pecho brillan granos dorados que canalizan su energía vital.
Se mueve sigilosamente entre los campos, acechando como un guardián natural del suelo. Sus hojas-lanza pueden cortar incluso roca blanda, y su cuerpo flexible le permite esquivar ataques con elegancia.
Cuando corre, las vetas doradas de sus hojas se encienden, dejando un destello que parece la estela del sol sobre un mar de maíz.`, stats: { hp: 75, atk: 100, def: 80, spa: 50, spd: 70, spe: 95, total: 470 }, evolutionLine: [72, 73]},
  {id: 74, name: "Nimbin", types: ["Fantasma"], image: "Sprite/Nimbin.png", definition: "Gato sueño", dex_draft: `Nimbín pasa gran parte del día dormitando entre raíces, piedras o rincones tranquilos. Aunque parezca profundamente dormido, sus enormes orejas perciben todo lo que ocurre a su alrededor. Se dice que los sueños de otros Pokémon suelen atraer su curiosidad.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [74, 75, 76]},
  {id: 75, name: "Velurio", types: ["Fantasma"], image: "Sprite/Velurio.png", definition: "Gato onirico", dex_draft: `Cuando evoluciona, Velurio comienza a pasar más tiempo vagando durante la noche. Sus marcas oscuras cambian lentamente de forma mientras duerme, reflejando fragmentos de sueños que ha observado durante sus viajes.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [74, 75, 76]},
  {id: 76, name: "Oniryn", types: ["Fantasma"], image: "Sprite/Oniryn.png", definition: "Gato pesadilla", dex_draft: `Las antiguas leyendas de Aionia afirman que esta especie puede caminar entre los límites del sueño y la realidad. Allí donde descansa durante varias noches, otros Pokémon aseguran recordar lugares que nunca han visitado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [74, 75, 76]},
  {id: 80, name: "Alchi", types: ["Agua", "Hielo"], image: "Sprite/Alchi.png", definition: "Alcas de los Acantilados", dex_draft: `Alchi nace cubierto por un grueso plumón que le permite soportar los fuertes vientos de la costa norte de Aionia. Su pico crece rápidamente durante los primeros meses de vida, alcanzando proporciones que parecen desmesuradas para su pequeño cuerpo.

Permanece cerca de las colonias de adultos, observando atentamente cada inmersión antes de aventurarse por sí mismo al mar.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [80, 81]},
  {id: 81, name: "Picarca", types: ["Agua", "Hielo"], image: "Sprite/Picarca.png", definition: "Alcas de los Acantilados", dex_draft: `Picarca pasa la mayor parte de su vida en aguas frías y profundas, donde persigue bancos de peces mediante rápidas inmersiones. Sus alas se han adaptado para impulsarlo bajo el agua con una agilidad comparable a la de los Pokémon marinos más veloces.

Las marcas que aparecen sobre su pico se acumulan con el paso de los años. Los ejemplares más veteranos poseen patrones complejos que reflejan décadas de pesca en los mares del norte.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [80, 81]},
  {id: 88, name: "Velusa", types: ["Veneno", "Volador"], image: "Sprite/Velusa.png", definition: "Pokemon flotante", dex_draft: `Velusa flota sobre las corrientes costeras gracias a la gran vela membranosa que crece sobre su cuerpo. Aunque conserva pequeños tentáculos venenosos bajo la cabeza, apenas los utiliza para defenderse. Los grupos de Velusa suelen desplazarse durante días enteros siguiendo los mismos vientos oceánicos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [88, 89]},
  {id: 89, name: "Caravela", types: ["Veneno", "Volador"], image: "Sprite/Caravela.png", definition: "Coloso flotante", curiosidades: "Los tentáculos de Velusa contienen la mayor parte de su veneno. Al evolucionar a Caravela, las toxinas se trasladan a la propia vela, que segrega una fina película venenosa sobre toda su superficie.", dex_draft: `Con la madurez, la mayor parte de sus tentáculos se atrofian y su enorme vela se desarrolla hasta ocupar casi todo su cuerpo. Es capaz de recorrer cientos de kilómetros sin batir ninguna aleta, aprovechando las corrientes atmosféricas como un velero viviente. Las gotas tóxicas que se acumulan en los bordes de su vela pueden irritar gravemente a cualquier depredador que intente atraparlo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [88, 89]},
  {id: 92, name: "Nautini", types: ["Agua", "Hada"], image: "Sprite/Nautini.png", definition: "Pokémon Nautilo", dex_draft: `Nautini flota cerca de arrecifes tranquilos y praderas marinas, donde se alimenta de diminutos organismos suspendidos en el agua. Las cinco cámaras visibles de su concha le permiten ajustar su flotabilidad con gran precisión, desplazándose suavemente con las corrientes. Se siente atraído por lugares donde el mar permanece en calma durante largos periodos de tiempo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [92, 93, 94]},
  {id: 93, name: "Spirilume", types: ["Agua", "Hada"], image: "Sprite/Spirilume.png", definition: "Pokémon Espiral Marina", dex_draft: `A medida que madura, Spirilume desarrolla nuevas cámaras en su concha y largas aletas membranosas que utiliza para navegar por corrientes profundas. Se le suele observar recorriendo grandes distancias entre arrecifes, siguiendo rutas migratorias que repite generación tras generación. Sus ocho cámaras mantienen un equilibrio perfecto entre estabilidad y movilidad, permitiéndole flotar durante horas sin apenas esfuerzo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [92, 93, 94]},
  {id: 94, name: "Aurelith", types: ["Agua", "Hada"], image: "Sprite/Aurelith.png", definition: "Pokémon Espiral Áurea", dex_draft: `La concha de Aurelith continúa creciendo siguiendo patrones que aparecen de forma natural en numerosas especies marinas. Sus trece cámaras internas le permiten regular la flotabilidad con una precisión extraordinaria, permaneciendo inmóvil incluso en aguas agitadas. Los ejemplares más ancianos recorren océanos enteros y son capaces de regresar, años después, al mismo arrecife donde nacieron.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [92, 93, 94]},
  {id: 98, name: "Nivet", types: ["Hielo"], image: "Sprite/Nivet.png", definition: "Armiño de las Ventiscas", dex_draft: `Nivet se oculta bajo la nieve aprovechando su pelaje blanco para pasar desapercibido. Aunque suele parecer curioso e inofensivo, es un cazador sorprendentemente paciente para su tamaño.

Su característica cola de punta oscura permanece visible incluso durante las tormentas, permitiendo a otros miembros de su especie seguir sus movimientos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [98, 99]},
  {id: 99, name: "Mustyr", types: ["Hielo", "Siniestro"], image: "Sprite/Mustyr.png", definition: "Armiño de las Ventiscas", dex_draft: `Mustyr es un depredador especializado en regiones cubiertas de nieve y hielo. Su cuerpo flexible le permite desplazarse por túneles estrechos y lanzarse sobre sus presas con gran precisión.

Durante el invierno resulta extremadamente difícil distinguirlo del paisaje. Muchos Pokémon solo perciben su presencia cuando ya es demasiado tarde para escapar.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [98, 99]},
  {id: 100, name: "Solunix", types: ["Hada", "Psíquico"], image: "Sprite/Solunix.png", definition: "Pokémon Crepúsculo", curiosidades: "Cuando el sol comienza a desaparecer tras el horizonte, los Risillo que viven en su pelaje despiertan y llenan el aire de pequeñas luces danzantes. Los grupos de Solunix utilizan estos destellos para mantenerse unidos incluso en la oscuridad.  \n\nDurante siglos se creyó que Risillo era una simple manifestación luminosa producida por Solunix. Estudios recientes demostraron que se trata de un organismo simbionte real que completa todo su ciclo vital asociado a un huésped de esta especie.\n\nLos habitantes de Aionia creen que los primeros Risillo nacieron de las risas compartidas durante los largos atardeceres de verano. Aunque los investigadores consideran que se trata de una leyenda, nadie ha conseguido explicar por qué las colonias de Solunix prosperan especialmente en lugares donde las reuniones y celebraciones son frecuentes.", dex_draft: `Solunix mantiene una relación simbiótica con pequeños organismos luminosos llamados Risillo, que habitan entre su espeso pelaje. Durante el día permanecen ocultos y apenas muestran actividad, pero al atardecer despiertan y comienzan a emitir suaves destellos de luz.

Las colonias de Solunix suelen reunirse en colinas y claros abiertos para contemplar la puesta de sol. Los Risillo intercambian señales luminosas entre individuos cercanos, creando patrones brillantes que recuerdan a un cielo lleno de estrellas.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [100]},
  {id: 111, name: "Briscorn", types: ["Hielo"], image: "Sprite/Briscorn.png", definition: "Cabrita de las Nieves", dex_draft: `Briscorn habita los acantilados más fríos de Aionia, donde las ventiscas soplan durante gran parte del año. Sus pequeños cuernos absorben agua de la nieve y la niebla marina, formando finas capas de hielo sobre su superficie.

Los ejemplares jóvenes pasan gran parte de su tiempo escalando riscos imposibles y compitiendo entre ellos para alcanzar los lugares más expuestos al viento.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [111, 112]},
  {id: 112, name: "Ventrago", types: ["Hielo", "Lucha"], image: "Sprite/Ventrago.png", definition: "Cabra de las Nieves", dex_draft: `Con la edad, los cuernos de Ventrago continúan creciendo mediante sucesivas capas de hielo moldeadas por el clima. Ningún individuo desarrolla la misma forma, ya que cada montaña y cada corriente de aire dejan patrones únicos sobre ellos.

Su poderosa musculatura le permite recorrer pendientes casi verticales sin perder el equilibrio. Durante la época de apareamiento, los machos chocan sus enormes cuernos produciendo ecos que resuenan por los valles nevados.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [111, 112]},
  {id: 120, name: "Talom", types: ["Roca", "Fantasma"], image: "Sprite/Talom.png", definition: "Pokémon Autómata Lítico", dex_draft: `Talom es un gólem creado por una civilización antigua especializada en la geometría sagrada y la animación ritual de la piedra. Su cuerpo está compuesto por bloques minerales encajados con precisión, unidos por un núcleo energético sellado en su interior. Carece de rasgos faciales visibles; su conciencia se manifiesta como dos luces que emergen desde la cavidad de su yelmo. Era utilizado para labores de construcción, custodia y transporte en ciudades ceremoniales, permaneciendo inerte durante siglos hasta ser activado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [120, 121]},
  {id: 121, name: "Talurak", types: ["Roca", "Fantasma"], image: "Sprite/Talurak.png", definition: "Pokémon Coloso Ancestral", dex_draft: `Talurak es la evolución de Talom tras absorber grandes cantidades de energía ritual y minerales refinados. Su estructura se vuelve más compleja y estable, reforzada por anillos pétreos y conductos dorados que distribuyen la fuerza desde su núcleo central. Fue diseñado como guardián perpetuo de templos, caminos sagrados y enclaves históricos. A diferencia de otros gólems, Talurak no obedece órdenes directas: actúa únicamente cuando percibe una alteración grave del equilibrio del territorio que protege.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [120, 121]},
  {id: 122, name: "Lapiantis", types: ["Agua", "Planta"], image: "Sprite/Lapiantis.png", definition: "Pokemon pantano", curiosidades: "Se cree que las plantas que crecen sobre su caparazón establecen un vínculo simbiótico con él: absorben su energía vital a cambio de protegerlo del sol y los parásitos.", dex_draft: `Lapiantis es el antepasado de Lapras, una criatura que habitaba los pantanos y lagunas templadas mucho antes de que su especie migrara a los mares helados.
Su caparazón estaba cubierto de musgo y flores silvestres que crecían gracias a los nutrientes que acumulaba en su piel húmeda. Se desplazaba lentamente entre los juncos, camuflándose con la vegetación y ofreciendo su espalda como refugio a pequeños Pokémon acuáticos.
En lugar de comunicarse mediante cánticos, Lapiantis emitía sonidos graves y burbujeantes que se confundían con el murmullo del agua, lo que lo convertía en un ser tan pacífico como enigmático.`, stats: { hp: 130, atk: 85, def: 75, spa: 90, spd: 95, spe: 60, total: 535 }, evolutionLine: [122]},
  {id: 130, name: "Ferrabuto", types: ["Acero", "Agua"], image: "Sprite/Ferrabuto.png", definition: "Cúpula Antigua", dex_draft: `Ferrabuto protegía su blando cuerpo con una cúpula de mineral pulido que se endurecía con los siglos. Vivía pegado al fondo marino, filtrando nutrientes y ocultándose de depredadores bajo la arena.
Cuando detecta vibraciones, retrae sus patas y se cierra por completo, volviéndose indistinguible de una roca.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [130, 131]},
  {id: 131, name: "Sideratops", types: ["Acero"], image: "Sprite/Sideratops.png", definition: "Pokémon Arma", dex_draft: `La evolución de Ferrabuto que emergió cuando los mares se retiraron. Su caparazón se alargó en filosas cuchillas con las que cazaba y defendía su territorio.
Sus movimientos eran tan precisos que podía cortar la corriente marina a su paso.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [130, 131]},
  {id: 132, name: "Ammonyte", types: ["Tierra"], image: "Sprite/Ammonyte.png", definition: "Pokémon Espiral", dex_draft: `Ammonyte vive semienterrado en los pantanos, usando sus tentáculos para remover el fango y buscar nutrientes. Su concha, dura y porosa, le permite flotar durante las crecidas del río sin hundirse.
A menudo se le ve girando lentamente sobre sí mismo, filtrando el barro para extraer materia orgánica.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [132, 133]},
  {id: 133, name: "Ammostar", types: ["Tierra"], image: "Sprite/Ammostar.png", definition: "Pokémon Espiral", dex_draft: `La evolución de Ammonyte ha desarrollado una concha más resistente y cubierta de púas naturales que usa para intimidar a sus rivales.
En época de lluvias, patrulla los humedales con movimientos torpes pero firmes, dejando surcos en el lodo que sirven de refugio a otros Pokémon pequeños. Cuando se siente amenazado, se enrolla dentro de su concha y rueda, levantando una nube de barro que le sirve de camuflaje.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [132, 133]},
  {id: 134, name: "Aetherax", types: ["Volador"], image: "Sprite/Aetherax.png", definition: "Ave Primigenia", dex_draft: `Aetherax es considerado el antepasado directo de Aerodactyl, una criatura que dominó los cielos de Aionia antes de la fractura temporal.
A diferencia de su descendiente fosilizado, Aetherax posee un plumaje fino y oscuro que le permite regular la temperatura durante sus vuelos a gran altura.
Su estructura ósea es ligera pero resistente, y sus alas producen un silbido profundo al batir el aire, sonido que los antiguos habitantes interpretaban como el rugido del cielo.`, stats: { hp: 85, atk: 110, def: 70, spa: 65, spd: 65, spe: 120, total: 515 }, evolutionLine: [134]},
  {id: 135, name: "Gekolit", types: ["Eléctrico"], image: "Sprite/Gekolit.png", definition: "Pokémon Chispagecko", dex_draft: `Gekolit pasa gran parte del día trepando por troncos y paredes rocosas. Las almohadillas de sus patas acumulan electricidad estática a medida que se desplaza, liberando pequeñas chispas cuando se sobresalta. Sus dedos están cubiertos por millones de diminutas escamas adhesivas que le permiten desplazarse incluso por superficies completamente verticales. Aunque es muy territorial, rara vez resulta agresivo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [135, 136, 137]},
  {id: 136, name: "Gekorun", types: ["Eléctrico"], image: "Sprite/Gekorun.png", definition: "Pokémon Derrape", dex_draft: `Al alcanzar gran velocidad, Gekorun frota su vientre contra la arena seca para generar electricidad estática. Las membranas de sus extremidades delanteras le permiten realizar breves planeos mientras cambia de dirección en plena carrera. Habita zonas áridas y acantilados costeros. Su cuerpo alargado y aerodinámico está especializado para la velocidad, pudiendo recorrer grandes distancias sin detenerse.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [135, 136, 137]},
  {id: 137, name: "Voltrake", types: ["Eléctrico", "Dragón"], image: "Sprite/Voltrake.png", definition: "Pokémon Corriente", curiosidades: "Los antiguos marineros de Aionia observaban el vuelo de los Voltrake para predecir cambios de tiempo. Cuando varios individuos ascendían en espiral sobre los acantilados, era señal de que una tormenta se aproximaba desde el mar.", dex_draft: `Voltrake utiliza las corrientes térmicas para permanecer horas en el aire sin apenas mover las alas. La electricidad que recorre sus membranas le permite percibir cambios atmosféricos imperceptibles para otros Pokémon. Considerado el rey de los acantilados de Aionia, puede recorrer cientos de kilómetros siguiendo las corrientes ascendentes del océano. Su cuerpo ligero y flexible prioriza la eficiencia del vuelo sobre la fuerza bruta.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [135, 136, 137]},
  {id: 147, name: "Noxal", types: ["Siniestro", "Fantasma"], image: "Sprite/Noxal.png", definition: "El Fénix del Crepúsculo", dex_draft: `Cuando la última luz del día se apaga, Noxal abre sus alas. Dicen que nació del primer atardecer, cuando el fuego de Aerion necesitó un final para poder renacer. Es el guardián del reposo, la voz del silencio que sigue al paso del tiempo. Sus plumas absorben la luz y su vuelo deja un eco que se desvanece lentamente, como el último segundo de un reloj antes de detenerse.
En su pecho arde una geoda púrpura, el corazón de la noche, que late al ritmo del universo moribundo. Se dice que Noxal no destruye, sino que libera: apaga lo que sufre para devolverlo al vacío de donde vino. Su enfrentamiento con Aerion no fue por odio, sino por equilibrio; sin embargo, su conflicto incesante provocó que Kaironos perdiera el control. Cuando se cierne sobre el cielo, incluso las estrellas parecen inclinarse ante su vuelo, temiendo el momento en que todo vuelva a la oscuridad.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [147]},
  {id: 148, name: "Helion", types: ["Fuego", "Hada"], image: "Sprite/Helion.png", definition: "El Horizonte del Amanecer", dex_draft: `Helion nació del primer destello de luz que rompió la oscuridad del mundo. Representa el impulso vital, la chispa que hace avanzar el tiempo y enciende el deseo de creación. Su cuerpo irradia calor y serenidad, y sus pasos dejan flores que se marchitan al instante, símbolo del ciclo eterno del nacimiento y la pérdida.
Cuando extiende sus astas llameantes, el amanecer se alza incluso en noches sin sol. Los antiguos textos de Aionia cuentan que su voz podía acelerar el crecimiento de los bosques o hacer que las montañas se levantaran en un solo día. Sin embargo, su ansia de ver al mundo avanzar sin detenerse provocó desequilibrio en el flujo del tiempo. Su resplandor fue tan intenso que encendió la ira de Noxal y la desesperación de Kaironos, dando inicio al cataclismo temporal. En las leyendas, Helion no es solo la luz del día: es el deseo eterno de seguir adelante, sin mirar atrás.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [148]},
  {id: 149, name: "Kaironos", types: ["Dragón", "Psíquico"], image: "Sprite/Kaironos.png", definition: "Núcleo del Colapso", dex_draft: `Hace diez mil años, Kaironos sintió el peso de cada instante que existía. Su mente percibía el pasado, el presente y el futuro al mismo tiempo, una visión infinita que ningún ser podía soportar. Se dice que su rugido no fue de furia, sino de desesperación, y que con él quebró la corriente del tiempo. En un solo segundo, arrastró al mundo de Aionia miles de años hacia adelante, dejando cicatrices que aún distorsionan la realidad.
Su cuerpo, formado por fragmentos suspendidos de engranajes y relojes, flota en un equilibrio imposible, como si se mantuviera unido por pura voluntad. Aunque muchos lo temen, Kaironos no busca destrucción: intenta restaurar el flujo que rompió. Los pocos que lo han visto afirman que cuando abre sus alas, el aire se detiene y los relojes dejan de marcar la hora, como si el universo contuviera la respiración ante el guardián del tiempo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0, total: 0 }, evolutionLine: [149]}
];
