// ============================================================
// data-lugares.js
// Generado automáticamente por helper_lugares.py
// NO EDITAR A MANO: modifica el Excel y vuelve a generar.
// ============================================================

const LUGARES = [
  {
    "id": "Z001",
    "nombre": "Campamento Alpha",
    "descripcion": "Punto de partida del viaje y primer asentamiento humano de Aionia. Entre módulos científicos prefabricados y casas de madera, el lugar respira aire de expedición y descubrimiento. Aquí reside el Profesor (aún sin nombre), junto a los investigadores de la FEA, que orientan a los nuevos entrenadores y les entregan su primer compañero. El campamento se abre al mar mediante un muelle modesto donde faenan pescadores locales. Su orientación sur y el clima templado le dan una atmósfera cálida y acogedora.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z001.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": false,
      "puerto": true,
      "investigacion": true,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z002",
    "nombre": "Ruta 1",
    "descripcion": "Una pequeña franja costera que combina playa y pradera. Más adelante podrá recorrerse con Surf, pero al inicio sirve como primera zona de exploración. El sendero asciende por una colina cubierta de hierba alta, donde aparecen los primeros Pokémon salvajes. Desde su cima se divisa la entrada al Bosque Brumoria.",
    "tipo": "Ruta",
    "bioma": "Prado",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z002.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": [
      {
        "entorno": "Hierba",
        "pokemonId": 24,
        "pokemon": "Topin",
        "aparicion": 50.0,
        "nivelMin": 3,
        "nivelMax": 6,
        "turno": "Cualquiera"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 10,
        "pokemon": "Brilluga",
        "aparicion": 50.0,
        "nivelMin": 4,
        "nivelMax": 6,
        "turno": "Noche"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 13,
        "pokemon": "Claynip",
        "aparicion": 50.0,
        "nivelMin": 4,
        "nivelMax": 6,
        "turno": "Día"
      }
    ]
  },
  {
    "id": "Z003",
    "nombre": "Bosque Brumoria Sur",
    "descripcion": "Entrada meridional del bosque más emblemático de Aionia. Esta zona, más clara y templada, está llena de pequeños insectos, mamíferos y aves. El acceso principal se encuentra únicamente desde Ruta 1, siendo un tramo corto pero lleno de vida. El follaje forma un dosel luminoso donde la luz del amanecer se filtra suavemente.",
    "tipo": "Bosque",
    "bioma": "Bosque",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z003.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": [
      {
        "entorno": "Hierba",
        "pokemonId": 18,
        "pokemon": "Solfinch",
        "aparicion": 15.0,
        "nivelMin": 5,
        "nivelMax": 8,
        "turno": "Día"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 21,
        "pokemon": "Noctavi",
        "aparicion": 15.0,
        "nivelMin": 5,
        "nivelMax": 8,
        "turno": "Noche"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 10,
        "pokemon": "Brilluga",
        "aparicion": 40.0,
        "nivelMin": 4,
        "nivelMax": 8,
        "turno": "Noche"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 11,
        "pokemon": "Crisvolt",
        "aparicion": 20.0,
        "nivelMin": 7,
        "nivelMax": 9,
        "turno": "Noche"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 13,
        "pokemon": "Claynip",
        "aparicion": 40.0,
        "nivelMin": 4,
        "nivelMax": 8,
        "turno": "Día"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 14,
        "pokemon": "Pupterra",
        "aparicion": 20.0,
        "nivelMin": 7,
        "nivelMax": 9,
        "turno": "Día"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 24,
        "pokemon": "Topin",
        "aparicion": 20.0,
        "nivelMin": 5,
        "nivelMax": 9,
        "turno": "Cualquiera"
      },
      {
        "entorno": "Hierba",
        "pokemonId": 16,
        "pokemon": "Mossnip",
        "aparicion": 5.0,
        "nivelMin": 3,
        "nivelMax": 7,
        "turno": "Cualquiera"
      }
    ]
  },
  {
    "id": "Z004",
    "nombre": "Ruta 2",
    "descripcion": "Ruta marítima que por primera vez se cruza en barco. Al llegar al otro extremo, en el puerto entregan el permiso o la habilidad Surf, permitiendo volver a recorrerla libremente tras obtener la primera medalla. Las aguas son tranquilas, con bancos de peces luminosos y restos de plataformas de investigación flotando a la deriva.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z004.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z005",
    "nombre": "Isla Mazí",
    "descripcion": "Pequeña isla de investigación marina y primer destino importante del viaje. Aquí se encuentra el Primer Gimnasio de la FEA, especializado en Pokémon de tipo Planta, sencillo pero simbólico. El pueblo está formado por cabañas costeras y un centro de estudios oceanográficos dedicado a las especies aisladas de la zona.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 1,
    "imagen": "imagenes/lugares/Z005.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": true,
      "investigacion": true,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z006",
    "nombre": "Ruta 3",
    "descripcion": "Pequeña senda interior que cruza la isla Mazí de este a oeste. La parte central es una ruta rural con zonas de pesca y vegetación baja; al llegar al lado opuesto, la ruta se transforma en un tramo marítimo frecuentado por pescadores y científicos.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z006.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z007",
    "nombre": "Islote de Irémia",
    "descripcion": "Isla tranquila de ambiente artesanal y cultural. Sus habitantes viven del mar y de la creación manual: tejidos, tallas de madera y utensilios de pesca. Es un lugar sereno donde los entrenadores suelen detenerse antes de continuar su viaje.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z007.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z008",
    "nombre": "Cueva Irémia",
    "descripcion": "Sistema de cuevas de origen marino excavado bajo el islote de Irémia. Durante siglos, el agua ha modelado galerías de roca caliza, formando lagunas cristalinas y pequeñas playas ocultas. Sus zonas más profundas permanecen prácticamente inexploradas y albergan especies adaptadas a la oscuridad permanente.",
    "tipo": "Cueva",
    "bioma": "Cueva",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z008.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z009",
    "nombre": "Ruta 4",
    "descripcion": "Une la isla Irémia con un cenote escondido en el interior. La ruta ofrece un contraste de ecosistemas: playas abiertas, laderas cubiertas de hierba alta y un cenote con una gruta marina que alberga especies únicas. Es un punto de gran belleza natural y biodiversidad.",
    "tipo": "Ruta",
    "bioma": "Lago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z009.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z010",
    "nombre": "Ruta 5",
    "descripcion": "Extensión marítima que conecta la isla Irémia con el Puesto Delta. Es una travesía de aguas profundas y corrientes suaves, donde suelen encontrarse Pokémon pelágicos y viajeros.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z010.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z011",
    "nombre": "Puesto Delta",
    "descripcion": "Asentamiento costero similar al Campamento Alpha, habitado por investigadores, obreros y familias que están fundando una nueva ciudad. Desde aquí se extienden tres rutas en distintas direcciones, marcando el inicio de la expansión humana hacia el interior de Aionia.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 2,
    "imagen": "imagenes/lugares/Z011.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": true,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z012",
    "nombre": "Ruta 6",
    "descripcion": "Ruta costera que bordea playas de arena clara y da acceso a las pequeñas Islas Dysi, hogar de Pokémon acuáticos y crustáceos. Ideal para el entrenamiento de tipo Agua y las primeras exploraciones submarinas.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z012.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z013",
    "nombre": "Islas Dysi",
    "descripcion": "Pequeño archipiélago de islotes rocosos rodeados por arrecifes y praderas submarinas. Las corrientes suaves favorecen una enorme diversidad de Pokémon marinos y crustáceos. Sus playas apenas han sido alteradas por la presencia humana, convirtiéndose en uno de los mejores lugares para estudiar la biodiversidad costera.",
    "tipo": "Archipiélago",
    "bioma": "Archipiélago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z013.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z014",
    "nombre": "Ruta 7",
    "descripcion": "Camino interior que conecta el Puesto Delta con la Cueva Makriá, ubicada en la falda del monte del mismo nombre. Es un trayecto más frío y rocoso, cubierto de líquenes y piedras húmedas.",
    "tipo": "Ruta",
    "bioma": "Prado",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z014.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z015",
    "nombre": "Cueva Makriá",
    "descripcion": "Gran sistema de galerías volcánicas que atraviesa el interior del Monte Makriá. A medida que se desciende, el aire se vuelve cada vez más cálido y aparecen fumarolas, ríos de agua termal y antiguas cámaras de lava solidificada. En las profundidades aún persiste una intensa actividad geotérmica, creando uno de los ecosistemas más singulares de Aionia.",
    "tipo": "Cueva",
    "bioma": "Volcánico",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z015.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z016",
    "nombre": "Ruta 8",
    "descripcion": "Ruta fluvial que enlaza el Puesto Delta con el Puesto Beta, cruzando un río de aguas claras y frescas. A lo largo del trayecto, los entrenadores atraviesan praderas abiertas y pequeños puentes de madera.",
    "tipo": "Ruta",
    "bioma": "Río",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z016.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z017",
    "nombre": "Puesto Beta",
    "descripcion": "Núcleo en crecimiento a orillas de un río, habitado por pioneros que buscan fundar una comunidad estable en el interior. Este asentamiento conecta con la cara norte del Bosque Brumoria, más sombría y densa.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z017.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z018",
    "nombre": "Bosque Brumoria Norte",
    "descripcion": "Tramo septentrional del bosque, más frío, húmedo y cerrado. La niebla es frecuente y el ambiente más silencioso. Aquí los rayos de luz apenas alcanzan el suelo, y los Pokémon se han adaptado a un entorno más oscuro y misterioso.",
    "tipo": "Bosque",
    "bioma": "Bosque",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z018.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z019",
    "nombre": "Pueblo Kappa",
    "descripcion": "Localidad boscosa situada al norte del bosque, en una zona sombría resguardada por colinas. Desde aquí se divisan las montañas del norte de Aionia. Sus calles están flanqueadas por árboles antiguos, y la vida avanza tranquila entre sombras y claros de sol.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z019.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z020",
    "nombre": "Playa Notos",
    "descripcion": "Gran playa al sur de la colina donde se asienta el Pueblo Kappa. A diferencia del bosque sombrío, esta costa mira al sur y recibe sol todo el día. Sus acantilados y dunas forman uno de los paisajes más bellos de la región.",
    "tipo": "Playa",
    "bioma": "Playa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z020.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z021",
    "nombre": "Ruta 9",
    "descripcion": "Camino escarpado que asciende desde la Playa Notos hasta lo alto del acantilado. Desde este punto se contemplan vistas panorámicas del mar y de todas las poblaciones del sur, incluyendo las islas Mazí e Irémia. Un “cul de sac” natural, perfecto para contemplar el horizonte.",
    "tipo": "Ruta",
    "bioma": "Acantilado",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z021.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z022",
    "nombre": "Ruta 10",
    "descripcion": "Ruta de transición entre el bosque y las colinas agrícolas. Conecta el Pueblo Kappa con el Pueblo Spóros, y marca el inicio de una región más abierta, donde la vegetación se mezcla con campos de cultivo y molinos de viento.",
    "tipo": "Ruta",
    "bioma": "Prado",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z022.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z023",
    "nombre": "Pueblo Spóros",
    "descripcion": "Ciudad agrícola y laboriosa, centrada en el cultivo y la autosuficiencia. Sus habitantes trabajan los campos fértiles con dedicación, soñando con convertir la zona en el principal proveedor de alimentos de Aionia.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 3,
    "imagen": "imagenes/lugares/Z023.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": true,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z024",
    "nombre": "Ruta 11",
    "descripcion": "Llanura abierta donde soplan fuertes vientos, uniendo Spóros con el Pantano Telma. Es una zona de transición entre tierras fértiles y humedales.",
    "tipo": "Ruta",
    "bioma": "Pantano",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z024.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z025",
    "nombre": "Pantano Telma",
    "descripcion": "Pantano místico situado en el corazón de Aionia. Entre nieblas y raíces sumergidas se hallan ruinas cubiertas de inscripciones antiguas. En su interior se oculta el Santuario de Noxal, refugio de especies del cenagal y de guardianes olvidados.",
    "tipo": "Pantano",
    "bioma": "Pantano",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z025.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z026",
    "nombre": "Ruta 12",
    "descripcion": "Ruta interior que conecta la salida del pantano con Villa Anáchoma. Cruza un río y asciende por una zona rocosa al norte del Monte Makriá. El terreno cambia de húmedo a árido en pocos pasos, reflejando la variedad climática de la región.",
    "tipo": "Ruta",
    "bioma": "Río",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z026.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z027",
    "nombre": "Villa Anáchoma",
    "descripcion": "Villa construida junto al límite entre las tierras fértiles del centro de Aionia y las regiones más áridas del interior. Sus habitantes viven del comercio entre ambos territorios, convirtiéndola en un importante punto de descanso antes de atravesar el desierto o dirigirse hacia la costa oriental.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 4,
    "imagen": "imagenes/lugares/Z027.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z028",
    "nombre": "Monte Makriá",
    "descripcion": "Imponente macizo volcánico que domina el centro de Aionia. Aunque su cumbre permanece nevada durante buena parte del año debido a la altitud, su interior conserva un potente corazón geotérmico que alimenta fuentes termales, cuevas volcánicas y suelos ricos en minerales. Sus laderas presentan una gran variedad de ecosistemas, convirtiéndolo en uno de los lugares con mayor biodiversidad de la región.",
    "tipo": "Montaña",
    "bioma": "Volcánico",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z028.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z029",
    "nombre": "Ruta 13",
    "descripcion": "Camino sin salida que recorre una zona boscosa al norte del Monte Makriá, terminando en playas y praderas solitarias. Es un rincón tranquilo, apenas visitado por entrenadores.",
    "tipo": "Ruta",
    "bioma": "Playa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z029.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z030",
    "nombre": "Desierto Érimos",
    "descripcion": "Extensa ruta desértica que une Villa Anáchoma con el Bosque Voreio. Sol abrasador, dunas interminables y cielos de fuego al atardecer. Solo los más resistentes se atreven a cruzarlo.",
    "tipo": "Desierto",
    "bioma": "Desierto",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z030.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z031",
    "nombre": "Bosque Voreio",
    "descripcion": "Bosque soleado y abierto, poblado por árboles bajos que dejan pasar la luz dorada del sol. Su ambiente recuerda a los paisajes mediterráneos, con senderos arenosos y una playa al final desde la que se observan islas lejanas.",
    "tipo": "Bosque",
    "bioma": "Bosque",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z031.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z032",
    "nombre": "Ruta 14",
    "descripcion": "Saliendo al sur de Villa Anáchoma, esta ruta avanza hacia el este, cruzando dos ríos y bordeando el lago Limni. El camino serpentea entre árboles y praderas antes de llegar a la gran ciudad costera de Kolpos.",
    "tipo": "Ruta",
    "bioma": "Lago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z032.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z033",
    "nombre": "Lago Límni",
    "descripcion": "Gran lago de agua dulce alimentado por los ríos que descienden de las montañas. Sus orillas alternan juncales, playas de grava y pequeños bosques ribereños donde numerosas especies encuentran refugio. Es uno de los principales reservorios naturales de agua de toda la región.",
    "tipo": "Lago",
    "bioma": "Lago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z033.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z034",
    "nombre": "Ciudad Kolpos",
    "descripcion": "Enorme ciudad portuaria situada en una bahía imponente. Se proyecta como la futura capital de Aionia. Sus amaneceres dorados y atardeceres reflejados sobre el mar la convierten en uno de los paisajes más emblemáticos de la región.",
    "tipo": "Ciudad",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 5,
    "imagen": "imagenes/lugares/Z034.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": true,
      "investigacion": false,
      "observatorio": false,
      "mercado": true,
      "guarderia": true,
      "hotel": true
    },
    "encuentros": []
  },
  {
    "id": "Z035",
    "nombre": "Ruta 15",
    "descripcion": "Pequeña ruta costera situada al sur de Ciudad Kolpos. Combina playas tranquilas, senderos junto al mar y una amplia bahía de aguas calmadas donde embarcaciones pesqueras y científicas parten diariamente hacia las islas cercanas.",
    "tipo": "Ruta",
    "bioma": "Playa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z035.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z036",
    "nombre": "Bosque Naftilia",
    "descripcion": "Bosque mediterráneo que marca la transición entre la costa oriental y las montañas del norte. Pinos, encinas y matorrales aromáticos cubren sus senderos, mientras el terreno asciende poco a poco hasta conectar con las rutas de alta montaña.",
    "tipo": "Bosque",
    "bioma": "Bosque",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z036.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z037",
    "nombre": "Ruta 16",
    "descripcion": "Camino montañoso que asciende desde los bosques templados hasta las primeras cumbres nevadas de Aionia. La vegetación disminuye gradualmente mientras aparecen paredes de roca, cascadas y antiguos refugios de montaña.",
    "tipo": "Ruta",
    "bioma": "Montaña",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z037.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z038",
    "nombre": "Pueblo Thílaka",
    "descripcion": "Pequeño pueblo de montaña construido para soportar los duros inviernos del norte. Sus casas de piedra y tejados inclinados permanecen rodeadas de nieve durante buena parte del año, convirtiéndose en el principal punto de descanso para quienes desean explorar las altas cumbres.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 6,
    "imagen": "imagenes/lugares/Z038.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z039",
    "nombre": "Ruta 17",
    "descripcion": "Circuito de alta montaña que recorre las cumbres más elevadas de Aionia. El clima extremo, el hielo permanente y los fuertes vientos convierten esta ruta en una de las más exigentes para cualquier entrenador.",
    "tipo": "Ruta",
    "bioma": "Nieve",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z039.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z040",
    "nombre": "Ruta 18",
    "descripcion": "Larga ruta de descenso desde las montañas hasta la costa septentrional. Comienza entre acantilados escarpados y termina en extensas playas de arena fina bañadas por un mar mucho más frío y bravo que el del sur.",
    "tipo": "Ruta",
    "bioma": "Montaña",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z040.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z041",
    "nombre": "Pueblo Paralía",
    "descripcion": "Pueblo pesquero situado bajo los grandes acantilados de la costa norte. Sus habitantes han aprendido a convivir con el oleaje y los fuertes vientos, aprovechando las numerosas calas protegidas para la pesca y la navegación.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 7,
    "imagen": "imagenes/lugares/Z041.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": true,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z042",
    "nombre": "Ruta 19",
    "descripcion": "Ruta litoral que serpentea entre playas escondidas, calas de difícil acceso y pequeñas grutas abiertas por el mar. La constante erosión ha creado un paisaje espectacular donde conviven especies costeras y marinas poco frecuentes.",
    "tipo": "Ruta",
    "bioma": "Costa rocosa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z042.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z043",
    "nombre": "Gruta oscura",
    "descripcion": "Pequeña cueva marina parcialmente inundada, iluminada únicamente por la luz que se filtra desde el océano. Sus cámaras interiores permanecen envueltas en penumbra durante todo el día, creando un ecosistema único.",
    "tipo": "Cueva",
    "bioma": "Cueva",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z043.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z044",
    "nombre": "Ruta 20",
    "descripcion": "Antiguo camino de piedra que comunica Pueblo Thílaka con las ruinas del Templo de los Antiguos. A medida que el sendero asciende, los restos de construcciones ancestrales se hacen cada vez más frecuentes, anticipando la importancia histórica de la zona.",
    "tipo": "Ruta",
    "bioma": "Montaña",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z044.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z045",
    "nombre": "Templo de los antiguos",
    "descripcion": "Complejo ceremonial construido por la civilización que habitó Aionia mucho antes de la llegada de los colonos. Sus enormes columnas y pasillos de piedra aún conservan grabados cuyo significado permanece sin descifrar. En lo más profundo del templo se oculta un acceso secreto hacia el Refugio de los Antiguos.",
    "tipo": "Ruinas",
    "bioma": "Ruinas",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z045.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z046",
    "nombre": "Refugio de los Antiguos",
    "descripcion": "Asentamiento oculto donde los últimos descendientes de la antigua civilización continúan viviendo alejados del resto de habitantes de Aionia. Han preservado su arquitectura, conocimientos y tradiciones durante generaciones, manteniendo en secreto gran parte de la verdadera historia de la región.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z046.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": true,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z047",
    "nombre": "Playa Kefali",
    "descripcion": "Extensa playa aislada que solo puede visitarse tras los acontecimientos finales relacionados con los legendarios de Aionia. Sus praderas costeras y dunas albergan Pokémon de gran nivel que apenas han tenido contacto con los humanos.",
    "tipo": "Playa",
    "bioma": "Playa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z047.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z048",
    "nombre": "Ruta 21",
    "descripcion": "Ruta marítima que conecta Playa Kefali con las Islas Asteri. Sus aguas son tranquilas y transparentes, rodeadas de pequeños islotes y bancos de arena donde abundan Pokémon marinos. Al final del recorrido se alza el Observatorio Akti, construido para estudiar el océano y los cielos de Aionia.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z048.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z049",
    "nombre": "Islas Asteri",
    "descripcion": "Pequeño archipiélago formado por varias islas de origen rocoso. En la isla principal se encuentra el Observatorio Akti y un reducido asentamiento de apenas unas pocas viviendas, cuyos habitantes viven volcados en el estudio del mar y de las corrientes oceánicas. Aquí se encuentra el octavo Gimnasio de Aionia, especializado en Pokémon de tipo Agua.",
    "tipo": "Pueblo",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": 8,
    "imagen": "imagenes/lugares/Z049.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": true,
      "puerto": true,
      "investigacion": false,
      "observatorio": true,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z050",
    "nombre": "Ruta 22",
    "descripcion": "Breve travesía marítima que une las Islas Asteri con un pequeño islote solitario perdido en el horizonte. No existen asentamientos ni caminos; únicamente una playa silenciosa desde la que el sol se oculta sobre el mar cada atardecer. Es un lugar apartado del bullicio, elegido por la Líder del Gimnasio para despedir a los entrenadores antes del último tramo de su viaje.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z050.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z051",
    "nombre": "Zona Desafio",
    "descripcion": "Recinto neutral construido conjuntamente por los colonos y los Antiguos para poner a prueba a los entrenadores más prometedores. Superar este desafío demuestra que el aspirante posee la fortaleza necesaria para enfrentarse a la Liga Pokémon de Aionia.",
    "tipo": "Ruta",
    "bioma": "Montaña",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z051.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z052",
    "nombre": "Bahía de Kolpos",
    "descripcion": "Amplia bahía de aguas tranquilas situada frente a Ciudad Kolpos. Sus corrientes suaves la convierten en la principal vía marítima de la región y en el punto de partida hacia las Islas Télos.",
    "tipo": "Ruta",
    "bioma": "Mar",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z052.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z053",
    "nombre": "islas Télos",
    "descripcion": "Dos pequeñas islas mediterráneas cubiertas por pinares, campos abiertos y playas de aguas cristalinas. Además de albergar la Liga Pokémon, son un importante enclave para la investigación y la conservación de especies costeras.",
    "tipo": "Archipiélago",
    "bioma": "Archipiélago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z053.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z054",
    "nombre": "Liga Pokemon",
    "descripcion": "La recién inaugurada Liga Pokémon de Aionia se alza sobre uno de los islotes Télos. En lugar de una Calle Victoria tradicional, los aspirantes deben superar previamente la Zona Desafío para demostrar que están preparados para enfrentarse al Alto Mando.",
    "tipo": "Liga",
    "bioma": "Urbano",
    "salvajes": false,
    "medalla": null,
    "imagen": "imagenes/lugares/Z054.png",
    "servicios": {
      "centroPokemon": true,
      "tienda": true,
      "gimnasio": false,
      "puerto": true,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": true
    },
    "encuentros": []
  },
  {
    "id": "Z055",
    "nombre": "Islas Trianta",
    "descripcion": "Archipiélago protegido formado por tres islas prácticamente intactas. Consideradas una gran reserva natural, albergan numerosas especies poco comunes y constituyen uno de los principales destinos del contenido posterior a la Liga.",
    "tipo": "Archipiélago",
    "bioma": "Archipiélago",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z055.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z056",
    "nombre": "Gruta chamilós",
    "descripcion": "Cueva semisumergida situada bajo la isla septentrional de Trianta. Sus cámaras, moldeadas por las mareas durante milenios, podrían servir de refugio a especies extremadamente raras.",
    "tipo": "Cueva",
    "bioma": "Cueva",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z056.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z057",
    "nombre": "Isla Notio",
    "descripcion": "Gran isla situada al suroeste de Aionia que ha permanecido aislada durante siglos. Su combinación de bosques, acantilados y playas solitarias ha favorecido la aparición de una fauna muy diferente a la del resto de la región.",
    "tipo": "Isla",
    "bioma": "Bosque mediterráneo",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z057.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  },
  {
    "id": "Z058",
    "nombre": "Isla Xirós",
    "descripcion": "Isla azotada constantemente por los vientos oceánicos. La vegetación es escasa y el paisaje está dominado por roca desnuda y acantilados, creando uno de los entornos más hostiles y misteriosos de toda Aionia.",
    "tipo": "Isla",
    "bioma": "Costa rocosa",
    "salvajes": true,
    "medalla": null,
    "imagen": "imagenes/lugares/Z058.png",
    "servicios": {
      "centroPokemon": false,
      "tienda": false,
      "gimnasio": false,
      "puerto": false,
      "investigacion": false,
      "observatorio": false,
      "mercado": false,
      "guarderia": false,
      "hotel": false
    },
    "encuentros": []
  }
];

// También lo exponemos explícitamente en window para facilitar
// el acceso desde las páginas HTML del proyecto.
window.LUGARES = LUGARES;
