// Archivo generado automáticamente desde pokemon.xlsx (hoja 'Hoja 2')
const POKEMON = [
  {id: 1, name: "Seedmind", types: ["Planta"], image: "Sprite/Seedmind.png", definition: "Semilla Mental", curiosidades: "Muchos entrenadores aseguran que las plantas florecen mejor cerca de un Seedmind en reposo.", dex_draft: `Un pequeño brote con una semilla brillante en su interior y dos hojas que recuerdan a orejas. Cuando Seedmind permanece inmóvil, el aire a su alrededor parece detenerse, como si el mundo contuviera la respiración.
Su semilla capta los pensamientos más simples de los seres cercanos —curiosidad, miedo o calma— y los transforma en débiles pulsos de energía que nutren su crecimiento.
A menudo se le ve inclinarse suavemente hacia quienes tienen una mente tranquila, como si reconociera un terreno fértil para sus raíces mentales.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 2, name: "Bloomind", types: ["Planta", "Psíquico"], image: "Sprite/Bloomind.png", definition: "Flor Mental", curiosidades: "Se dice que un grupo de Bloomind meditando en c\u00edrculo puede sincronizar sus pensamientos hasta compartir sue\u00f1os, creando jardines ilusorios donde las emociones florecen como p\u00e9talos.", dex_draft: `Bloomind marca el florecimiento de la conciencia de Seedmind. Su cuerpo es más alto y firme, y en la cima de su cabeza brota una flor en espiral que pulsa con luz suave al ritmo de sus pensamientos.
Cuando Bloomind concentra su mente, el entorno se llena de un aroma sutil que refleja su estado emocional: dulce cuando está en calma, y punzante cuando percibe peligro.
Su poder psíquico le permite comunicarse mediante ondas mentales que apenas alteran el aire, creando una sensación de serenidad incluso en pleno combate.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 3, name: "Floracere", types: ["Planta", "Psíquico"], image: "Sprite/Floracere.png", definition: "Flor Mental", curiosidades: "Se dice que cuando un Floracere medita en el coraz\u00f3n del bosque, el flujo del tiempo se ralentiza y las flores brotan fuera de temporada.", dex_draft: `Floracere canaliza su energía vital a través de los pétalos fucsia que coronan su cabeza, los cuales vibran al unísono con sus pensamientos.
Su cuerpo esbelto y flotante le permite desplazarse sin mover el aire, como si la gravedad misma lo respetara.
Es conocido por su serenidad absoluta: su sola presencia calma a los Pokémon y humanos que lo rodean.
En combate, sus hojas giran como pensamientos afilados, proyectando ondas psíquicas que desorientan al enemigo antes de atacar.`, stats: { hp: 1, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 4, name: "Cindimp", types: ["Fuego"], image: "Sprite/Cindimp.png", definition: "Gatito Brasa", curiosidades: "nan", dex_draft: `La llama que brota de su cabeza cambia de intensidad según su humor: crepita si se enfada y parpadea suavemente cuando ronronea. Tiene un carácter independiente, pero busca calor y compañía cuando confía en su entrenador.
Le gusta dormir en lugares templados, especialmente sobre piedras o metal caliente. Juega cazando chispas o su propia cola encendida, lo que a veces acaba en pequeños incendios accidentales.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 5, name: "Umbrazar", types: ["Fuego", "Siniestro"], image: "Sprite/Umbrazar.png", definition: "Felino \u00cdgneo", curiosidades: "nan", dex_draft: `Umbrazar mantiene la agilidad y curiosidad de Cindimp, pero su temperamento se vuelve más serio y territorial. Su cuerpo es más estilizado y fuerte, y la llama de su cabeza se divide en dos cuernos ardientes, símbolo de poder y madurez.
Es un cazador nocturno que se desliza silencioso, dejando tras de sí un rastro de calor. Su fuego arde con tonos anaranjados y rojizos, y puede envolver sus patas en llamas sin hacerse daño, lanzando zarpazos abrasadores.
En combate, se muestra confiado y táctico, prefiriendo acercarse sigilosamente antes de atacar con precisión felina.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 6, name: "Infernash", types: ["Fuego", "Siniestro"], image: "Sprite/Infernash.png", definition: "Felino \u00cdgneo", curiosidades: "Los entrenadores veteranos dicen que cuando Infernash conf\u00eda plenamente en su compa\u00f1ero, permite que su llama brille con un tono dorado, s\u00edmbolo de respeto mutuo.", dex_draft: `Su cuerpo desprende calor intenso incluso sin llamas visibles. Las grietas incandescentes de su pecho liberan fuego cada vez que ruge. Tiene  una mirada firme y desafiante.
Aunque parece agresivo, Infernash es un Pokémon leal y protector. Se dice que cuida su territorio con ferocidad, pero nunca ataca sin motivo. Sus rugidos son capaces de hacer vibrar el aire y asustar a enemigos a gran distancia.
Prefiere descansar en zonas volcánicas o arenosas, donde puede liberar calor sin riesgo de incendiar el entorno.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 7, name: "Fluwel", types: ["Agua"], image: "Sprite/Fluwel.png", definition: "Pu\u00f1o de Agua", curiosidades: "nan", dex_draft: `Fluwel es juguetón y valiente. Le encanta golpear el agua con sus pequeñas patas, creando ondas que usa para medir su fuerza. Cuando se concentra, el agua responde a sus movimientos como si bailara con él.
Aunque es curioso y algo cabezota, nunca huye de un desafío. Su cuerpo es ligero y flexible, y aprende rápido a moverse siguiendo el ritmo de las corrientes.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 8, name: "Ottrine", types: ["Agua", "Lucha"], image: "Sprite/Ottrine.png", definition: "Luchador de las Corrientes", curiosidades: "nan", dex_draft: `Ottrine se entrena en las orillas de los ríos, enfrentando el flujo del agua para fortalecer su cuerpo. Usa sus brazos y cola como remos, y sus movimientos son tan precisos que apenas levantan espuma.
Su expresión seria no engaña: es un Pokémon disciplinado que dedica cada día a perfeccionar su técnica. Cuando pelea, combina golpes rápidos con fluidos movimientos acuáticos que desconciertan al rival.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 9, name: "Marinoir", types: ["Agua", "Lucha"], image: "Sprite/Marinoir.png", definition: "Guerrero del Mar", curiosidades: "nan", dex_draft: `Marinoir domina la fuerza y el equilibrio del agua con absoluta maestría. Cada uno de sus movimientos está en armonía con la marea, capaz de desatar torrentes con un simple golpe.
Es un Pokémon noble y protector, que solo combate cuando es necesario. Se dice que puede desviar una ola entera con el impulso de sus brazos, y que su entrenamiento bajo cascadas dura días enteros sin descanso.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 10, name: "Brilluga", types: ["Bicho"], image: "Sprite/Brilluga.png", definition: "Larva de Luz", curiosidades: "nan", dex_draft: `Brilluga habita bajo la corteza de los árboles húmedos del Bosque Brumoria. Su cuerpo translúcido emite un resplandor tenue que usa para ahuyentar depredadores. Cuando varias se agrupan, sus luces se sincronizan formando un parpadeo rítmico que parece imitar el pulso del bosque. Los investigadores creen que esta especie regula la bioluminiscencia según las fases lunares.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 11, name: "Crisvolt", types: ["Bicho", "Eléctrico"], image: "Sprite/Crisvolt.png", definition: "Pupa Chispeante", curiosidades: "nan", dex_draft: `Durante su metamorfosis, Crisvolt se encierra en un capullo cristalino que acumula energía estática. Las descargas internas hacen vibrar el aire y generan un zumbido apenas audible que anuncia una tormenta próxima. En noches muy húmedas, su capullo brilla con luz azulada y actúa como faro para otras criaturas del bosque.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 12, name: "Voltasmoth", types: ["Bicho", "Eléctrico"], image: "Sprite/Voltasmoth.png", definition: "Luci\u00e9rnaga Nocturna", curiosidades: "nan", dex_draft: `Voltasmoth ilumina los claros del bosque con el destello de sus alas. Su vuelo crea patrones eléctricos que sirven de lenguaje entre individuos. Cuando una tormenta se aproxima, su cuerpo resplandece con fuerza y se dice que el cielo responde a su danza con relámpagos lejanos. Los antiguos Aionitas la consideraban un símbolo de guía y conocimiento.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 13, name: "Claynip", types: ["Bicho"], image: "Sprite/Claynip.png", definition: "Larva Terrera", curiosidades: "nan", dex_draft: `Claynip excava túneles en la tierra húmeda, reforzándolos con arcilla que amasa con sus propias secreciones. Vive en pequeñas colonias bajo las raíces, donde comparte calor con sus compañeras. Es común verlas competir por el mismo alimento que las larvas de Brilluga, aunque ambas especies rara vez se cruzan al mismo tiempo del día.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 14, name: "Pupterra", types: ["Bicho", "Tierra"], image: "Sprite/Pupterra.png", definition: "Capullo de Arcilla", curiosidades: "nan", dex_draft: `Pupterra se sella en una cámara de barro endurecido que construye ella misma. El calor del sol solidifica su envoltura, y los crujidos que emite al secarse indican el avance de su metamorfosis. Los científicos de la FEA han observado que sus capullos refuerzan el suelo y previenen la erosión en zonas inestables.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 15, name: "Terraphex", types: ["Bicho", "Tierra"], image: "Sprite/Terraphex.png", definition: "Arquitecta del Suelo", curiosidades: "nan", dex_draft: `Terraphex levanta nidos de barro perfectamente estructurados, donde almacena alimento y protege a su prole. Cada panal tiene una forma distinta según la composición del terreno. Sus alas levantan un polvo fino que endurece la tierra al contacto, y se dice que los antiguos Aionitas imitaban sus colmenas al construir sus templos subterráneos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 16, name: "Mossnip", types: ["Planta"], image: "Sprite/Mossnip.png", definition: "Conejo de Musgo", curiosidades: "nan", dex_draft: `Mossnip vive en los claros húmedos del Bosque, donde el sol apenas llega entre los árboles. Su pelaje, cubierto de musgo y pequeñas hojas, absorbe la humedad del aire y mantiene fresco el suelo donde descansa. Cuando se siente amenazado, se agacha y se inmoviliza, pareciendo un simple montículo verde. Su presencia indica un bosque sano y equilibrado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 17, name: "Thorabbit", types: ["Planta"], image: "Sprite/Thorabbit.png", definition: "Guardi\u00e1n del Bosque", curiosidades: "nan", dex_draft: `Thorabbit canaliza la energía vital del bosque a través del manto vegetal que cubre su cuerpo. Sus orejas largas, con nervaduras semejantes a hojas, captan los cambios de humedad y temperatura, permitiéndole anticipar tormentas. Donde salta, la hierba brota momentáneamente a su paso. Los antiguos Aionitas lo consideraban un espíritu protector de los claros sagrados, símbolo de fertilidad y renovación.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 18, name: "Solfinch", types: ["Volador", "Hada"], image: "Sprite/Solfinch.png", definition: "P\u00e1jaro Solar", curiosidades: "nan", dex_draft: `Solfinch despierta con el primer rayo de luz, extendiendo sus alas para absorber el calor del sol. Cuando canta, las gotas de rocío a su alrededor comienzan a brillar como diminutos soles. Es un Pokémon alegre y sociable que armoniza los ritmos del bosque al amanecer, marcando el inicio de cada nuevo día.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 19, name: "Aurelark", types: ["Volador", "Hada"], image: "Sprite/Aurelark.png", definition: "P\u00e1jaro del Alba", curiosidades: "nan", dex_draft: `Cuando el bosque comienza a calentar, Aurelark se eleva en espirales doradas, dispersando motas luminosas que nutren a los insectos y favorecen la floración. Sus alas vibran con tal velocidad que el aire a su alrededor se ondula, dejando un halo de luz suspendido. Representa la energía vital que enlaza a todos los seres con el amanecer.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 20, name: "Dawnazar", types: ["Volador", "Hada"], image: "Sprite/Dawnazar.png", definition: "Guardi\u00e1n del Amanecer", curiosidades: "nan", dex_draft: `Cuando los cielos de Aionia se tiñen de rosa, Dawnazar extiende sus alas y el bosque se inunda de luz. Cada pluma refleja los tonos del alba, y su canto disipa la niebla y ahuyenta la oscuridad. Donde vuela, renace la esperanza; su presencia anuncia el comienzo de un nuevo ciclo de vida.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 21, name: "Noctavi", types: ["Volador", "Fantasma"], image: "Sprite/Noctavi.png", definition: "P\u00e1jaro Crepuscular", curiosidades: "nan", dex_draft: `"Noctavi aparece cuando el bosque se sumerge en penumbra. Su llama etérea no quema ni ilumina: marca el límite entre la vigilia y el sueño. A menudo acompaña a los viajeros solitarios, flotando en silencio hasta el amanecer. Muchos lo confunden con un espíritu benigno, pero en realidad es un ave tímida que teme el ruido y la luz intensa. Su cresta espectral reacciona a las emociones humanas, y los antiguos Aionitas lo consideraban mensajero del alma dormida."`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 22, name: "Phaswift", types: ["Volador", "Fantasma"], image: "Sprite/Phaswift.png", definition: "P\u00e1jaro de Penumbra", curiosidades: "nan", dex_draft: `"Phaswift se entrena volando entre las corrientes de niebla. Su llama se intensifica cuando percibe energía vital cerca, lo que le permite detectar presencias invisibles. Dicen que si revolotea sobre un claro, significa que la bruma está viva y el bosque observa. Es un Pokémon curioso y silencioso, guía de otros nocturnos.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 23, name: "Umbraciel", types: ["Volador", "Fantasma"], image: "Sprite/Umbraciel.png", definition: "Guardi\u00e1n Espectral", curiosidades: "nan", dex_draft: `"Umbraciel reina sobre los cielos oscuros de Aionia. Su fuego frío atraviesa la niebla, iluminando solo aquello que desea mostrar. Protege el equilibrio entre la noche y el amanecer, y se dice que cuando su canto resuena, incluso los ecos del tiempo se detienen por respeto. Los textos Aionitas lo describen como el heraldo de Noxal, y se cree que sus alas pueden romper los límites entre los sueños y la realidad."`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 24, name: "Hedglow", types: ["Normal"], image: "Sprite/Hedglow.png", definition: "Pokemon erizo", curiosidades: "nan", dex_draft: `Hedglow habita bajo los arbustos y raíces del Bosque Brumoria. Es un Pokémon tranquilo y curioso que se enrolla para protegerse del peligro. Sus púas tienen una textura cálida y terrosa que lo camufla entre las hojas secas. Representa la vida sencilla y constante del suelo forestal.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 25, name: "Thornet", types: ["Normal"], image: "Sprite/Thornet.png", definition: "Pokemon puas", curiosidades: "nan", dex_draft: `La evolución de Hedglow desarrolla un carácter vigilante. Sus púas se endurecen con la edad, volviéndose tan resistentes como la corteza de un árbol. Thornet defiende su territorio con determinación, marcando el límite entre el bosque interior y las praderas abiertas. Su presencia simboliza la madurez y la protección del ciclo natural.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 26, name: "Magmorok", types: ["Roca", "Fuego"], image: "Sprite/Magmorok.png", definition: "Fragmento \u00cdgneo", curiosidades: "Cuando su temperatura interna desciende demasiado, busca grietas volc\u00e1nicas para \u201calimentar\u201d su fuego interno con calor y minerales fundidos.", dex_draft: `Magmarock es una roca viva nacida del magma aún joven de la Tierra. Su cuerpo está compuesto por piedra semisólida que rezuma lava líquida entre las grietas.
Aunque pequeño, su interior alberga un núcleo ardiente que nunca se apaga. Se mueve impulsándose con sus brazos como si escalara el suelo mismo, dejando marcas quemadas a su paso.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 27, name: "Magmorus", types: ["Roca", "Fuego"], image: "Sprite/Magmorus.png", definition: "N\u00facleo Fundente", curiosidades: "nan", dex_draft: `Magmorus es la forma evolucionada de Magmarock. Con el paso del tiempo, su cuerpo se ha compactado en varias capas de roca volcánica, aunque su núcleo sigue siendo inestable.
En su interior, el magma circula como sangre incandescente, dándole un aspecto brillante por las grietas.
Cuando se irrita o combate, libera gases ardientes que pueden provocar pequeñas explosiones a su alrededor.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 28, name: "Magmolith", types: ["Roca", "Fuego"], image: "Sprite/Magmolith.png", definition: "Coloso Bas\u00e1ltico", curiosidades: "nan", dex_draft: `Magmoliz representa el culmen de la evolución volcánica. Su cuerpo es casi una fortaleza de basalto endurecido que contiene en su interior un lago de magma perpetuo.
Cada paso que da hace vibrar el suelo, y su respiración expulsa vapor ardiente por las grietas de su coraza.
Pese a su apariencia imponente, se desplaza con lentitud y rara vez muestra agresión, actuando solo cuando siente que la tierra misma está amenazada.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 29, name: "Garrisk", types: ["Volador"], image: "Sprite/Garrisk.png", definition: "Pok\u00e9mon Merodeador Costero", curiosidades: "nan", dex_draft: `Garrisk habita playas rocosas, puertos abandonados y restos de naufragios recientes. Es extremadamente observador y paciente, permaneciendo inmóvil durante horas mientras vigila el horizonte en busca de actividad. Se alimenta de restos orgánicos arrastrados por las mareas y pequeños Pokémon debilitados. Aunque puede volar largas distancias, prefiere desplazarse a pie por la arena, usando su pico largo para rebuscar entre escombros y algas. Suele seguir a embarcaciones desde lejos, anticipando oportunidades.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 30, name: "Corvanta", types: ["Volador", "Siniestro"], image: "Sprite/Corvanta.png", definition: "Pok\u00e9mon Carro\u00f1ero de Naufragios", curiosidades: "nan", dex_draft: `Corvanta es un ave dominante de las costas peligrosas, donde abundan los restos de barcos hundidos. Su inteligencia y agresividad le permiten expulsar a otros carroñeros y reclamar zonas ricas en recursos. Aprovecha tormentas y mareas fuertes para localizar nuevos naufragios, guiándose por corrientes de aire y olores metálicos. Aunque rara vez ataca sin motivo, no duda en intimidar con despliegues de alas y graznidos ásperos. La presencia de Corvanta indica aguas traicioneras y actividad reciente en la costa.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 33, name: "Eeveon", types: ["Normal"], image: "Sprite/Eeveon.png", definition: "Pok\u00e9mon Primigenio", curiosidades: "nan", dex_draft: `Eeveon es el ancestro salvaje de Eevee, una criatura de instinto agudo y reflejos felinos que habitaba bosques densos y praderas abiertas antes de la intervención humana.
Su pelaje espeso y su estructura corporal más robusta lo protegían del clima y de los depredadores, mientras que su ADN, completamente estable, carecía aún de la inestabilidad genética que caracteriza a sus descendientes.
A diferencia de Eevee, su energía vital no fluctúa con el entorno: es una criatura centrada, pura, que representa el origen del linaje evolutivo más versátil conocido.`, stats: { hp: 60, atk: 70, def: 55, spa: 45, spd: 50, spe: 70 }},
  {id: 34, name: "Eeveoleon", types: ["Normal"], image: "Sprite/Eeveoleon.png", definition: "Pok\u00e9mon Evolutivo", curiosidades: "Algunos estudiosos creen que Evoleon representa lo que Eevee podr\u00eda llegar a ser si su ADN dejara de fragmentarse en posibles evoluciones, concentrando todo su potencial en una sola forma perfecta.", dex_draft: `Evoleon es la evolución natural y definitiva de Eeveeon, una forma perfeccionada que alcanzó el pináculo de la adaptación sin desviarse hacia ningún tipo elemental.
Su cuerpo, ágil y musculoso, mantiene una armonía total entre fuerza y precisión. Su mente, afinada por generaciones de evolución, le permite anticipar movimientos y mantener un dominio absoluto sobre su entorno.
Evoleon no necesita cambiar de tipo: su poder reside en la pureza misma de su naturaleza. En combate, se mueve con una mezcla de calma y ferocidad que refleja el equilibrio perfecto entre instinto y conciencia.`, stats: { hp: 85, atk: 95, def: 80, spa: 75, spd: 85, spe: 100 }},
  {id: 38, name: "Algoryn", types: ["Agua", "Planta"], image: "Sprite/Algoryn.png", definition: "Pok\u00e9mon Serpiente de Algas", curiosidades: "nan", dex_draft: `Algoryn habita lagunas costeras, praderas submarinas y zonas donde las algas crecen en abundancia. Su cuerpo flexible está cubierto por hojas vivas que brotan de su piel y se regeneran constantemente gracias a la luz solar. Estas algas le permiten camuflarse entre la vegetación marina y producir oxígeno incluso en aguas pobres. Se desplaza lentamente, dejándose llevar por las corrientes, y rara vez ataca, prefiriendo huir y confundirse con el entorno. Su presencia favorece la salud del ecosistema acuático.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 39, name: "Flamutt", types: ["Fuego"], image: "Sprite/Flamutt.png", definition: "Perro de fuego", curiosidades: "nan", dex_draft: `Flamutt nace con una pequeña llama en la cola, que crece conforme fortalece su valor. Vive en las praderas cálidas de Aionia, donde corre dejando pequeñas huellas humeantes en la hierba seca. Este Pokémon es curioso y valiente, aunque algo impulsivo.`, stats: { hp: 50, atk: 65, def: 45, spa: 60, spd: 50, spe: 80 }},
  {id: 40, name: "Flarehound", types: ["Fuego"], image: "Sprite/Flarehound.png", definition: "Perro de fuego", curiosidades: "nan", dex_draft: `Flarehound recorre las llanuras de Aionia dejando tras de sí senderos de fuego que las plantas locales utilizan para renacer más fuertes. Su carácter cambia con la madurez: leal y protector, nunca retrocede ante el peligro.`, stats: { hp: 80, atk: 110, def: 75, spa: 90, spd: 70, spe: 85 }},
  {id: 41, name: "Duneek", types: ["Tierra"], image: "Sprite/Duneek.png", definition: "Zorro de arena", curiosidades: "Los antiguos viajeros lo llamaban \u201cel eco del desierto\u201d, porque pod\u00edan escuchar sus pasos pero nunca verlo.", dex_draft: `Duneek vive oculto durante el día, enterrado bajo la arena caliente, y sale solo cuando cae la noche.
Sus grandes orejas detectan las vibraciones de los insectos bajo el suelo, permitiéndole cazar sin emitir un solo sonido.
Su pelaje claro refleja el sol y su nariz puede filtrar el aire cargado de polvo, lo que le permite sobrevivir en los desiertos más hostiles.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 42, name: "Noctennec", types: ["Tierra", "Siniestro"], image: "Sprite/Noctennec.png", definition: "Zorro nocturno", curiosidades: "nan", dex_draft: `La evolución de Duneek ocurre cuando perfecciona su dominio de la oscuridad y el silencio.
Noctennec se mueve como una sombra entre las dunas, dejando huellas que el viento borra al instante.
Sus ojos reflejan la luz de la luna con un brillo dorado, y se dice que puede confundir a sus presas proyectando ilusiones con su propio movimiento.
Caza solo, y los que han visto su silueta aseguran que no emite sonido alguno ni siquiera al respirar.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 53, name: "Dropletle", types: ["Bicho"], image: "Sprite/Dropletle.png", definition: "Escarabajo del Roc\u00edo", curiosidades: "nan", dex_draft: `Dropletle vive enterrado bajo la arena, dejando al descubierto solo el caparazón de su espalda, que brilla con diminutas gotas de agua condensada.
Durante la noche extiende sus alas para atrapar la humedad del aire frío, formando pequeñas perlas que almacena para hidratarse durante el día.
Se le considera un símbolo de esperanza en los desiertos más áridos, pues allí donde habita, las plantas parecen resistir mejor el calor.`, stats: { hp: 55, atk: 45, def: 70, spa: 35, spd: 75, spe: 40 }},
  {id: 54, name: "Hydrabeet", types: ["Bicho", "Agua"], image: "Sprite/Hydrabeet.png", definition: "Escarabajo del Vapor", curiosidades: "nan", dex_draft: `Hydrabeet ha desarrollado un sistema natural que convierte la humedad que almacena en vapor caliente, el cual libera por sus élitros para crear una neblina protectora.
En las madrugadas del desierto, su presencia cubre las dunas con un manto brillante que se asemeja a la niebla marina.
Su caparazón oscuro absorbe el calor del sol, y su cuerpo regula la presión interna para liberar chorros de vapor a modo de defensa o comunicación.`, stats: { hp: 80, atk: 65, def: 85, spa: 90, spd: 95, spe: 75 }},
  {id: 55, name: "Shellin", types: ["Agua"], image: "Sprite/Shellin.png", definition: "Pok\u00e9mon Caracol Marino", curiosidades: "nan", dex_draft: `Este Pokémon vive adherido a rocas costeras y utiliza su pequeño caparazón espiral para protegerse de las corrientes. Es lento y tímido, apenas puede disparar un chorrito de agua desde la punta de su concha. Su cuerpo gelatinoso le permite ocultarse en grietas húmedas cuando percibe peligro.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 56, name: "Shellump", types: ["Agua"], image: "Sprite/Shellump.png", definition: "Pok\u00e9mon Propulsor", curiosidades: "nan", dex_draft: `Su cuerpo se ha fortalecido y su caparazón ha comenzado a endurecerse. Puede expulsar chorros de agua a presión desde la parte superior para impulsarse bajo el mar. Vive en zonas de corrientes fuertes y compite con sus congéneres golpeando sus caparazones. Pequeñas lapas y verdín crecen sobre él, señal de su madurez.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 57, name: "Sheelljet", types: ["Agua"], image: "Sprite/Sheelljet.png", definition: "Pok\u00e9mon Turbina", curiosidades: "nan", dex_draft: `Un Pokémon poderoso que domina la presión del agua para defenderse y desplazarse. Su caparazón masivo actúa como una turbina natural: lanza chorros capaces de moverlo a gran velocidad o perforar rocas blandas. Se dice que cuando un Sheelljet se enfada, el sonido de su géiser puede oírse a kilómetros.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 63, name: "Corlin", types: ["Agua"], image: "Sprite/Corlin.png", definition: "Pok\u00e9mon Brote Coralino", curiosidades: "nan", dex_draft: `Corlín habita aguas costeras poco profundas donde la luz solar favorece el crecimiento de coral. Los pequeños apéndices de su cabeza son colonias coralinas vivas que se desarrollan en simbiosis con su cuerpo, obteniendo nutrientes de su piel húmeda. A cambio, el coral le proporciona camuflaje y absorbe toxinas del agua. Es un Pokémon dócil y curioso, que suele seguir a bancos de peces pequeños mientras explora el fondo marino.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 64, name: "Coralyn", types: ["Agua"], image: "Sprite/Coralyn.png", definition: "Pok\u00e9mon Coral Vivo", curiosidades: "nan", dex_draft: `A medida que Coralyn madura, el coral de su cabeza se ramifica y endurece, volviéndose más resistente a las corrientes fuertes. Este Pokémon migra hacia arrecifes más profundos, donde usa sus cuernos coralinos para anclarse y descansar sin ser arrastrado. Su piel secreta minerales que refuerzan las colonias coralinas, convirtiéndolo en un elemento clave para la regeneración de arrecifes dañados. Es pacífico, pero protege su territorio con firmeza.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 65, name: "Arrecor", types: ["Agua"], image: "Sprite/Arrecor.png", definition: "Pok\u00e9mon Guardi\u00e1n del Arrecife", curiosidades: "nan", dex_draft: `Arrecor es la forma final y más robusta de esta especie. Sus grandes cuernos coralinos albergan múltiples organismos marinos, formando un microecosistema móvil. Gracias a su gran masa y fuerza, estabiliza zonas del arrecife afectadas por tormentas o depredadores. Aunque su aspecto es imponente, rara vez ataca; prefiere intimidar y mantener el equilibrio natural de su entorno. La presencia de Arrecor es señal de un ecosistema marino sano y estable.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 72, name: "Mazorik", types: ["Planta"], image: "Sprite/Mazorik.png", definition: "Pok\u00e9mon Mazorca", curiosidades: "Se dice que las cosechas son m\u00e1s abundantes en los campos donde se esconde un Mazorik, aunque los agricultores raramente logran verlo.", dex_draft: `Mazorik habita en los campos fértiles donde crece el maíz silvestre. Su cuerpo redondeado, formado por granos dorados y hojas verdes envolventes, brilla al sol como una pequeña joya vegetal.
Es un Pokémon travieso que disfruta escondiéndose entre las plantas para lanzar semillas endurecidas a los intrusos. Sus movimientos rápidos entre los tallos hacen difícil atraparlo, y cuando se siente seguro, emite un leve crujido parecido al de las hojas secas al viento.
A medida que absorbe luz solar, sus granos se vuelven más brillantes, señal de que su energía está madurando para la evolución.`, stats: { hp: 55, atk: 65, def: 55, spa: 40, spd: 50, spe: 60 }},
  {id: 73, name: "Corstalk", types: ["Planta"], image: "Sprite/Corstalk.png", definition: "Pok\u00e9mon Espiga", curiosidades: "Algunos agricultores de Aionia consideran a Corstalk un esp\u00edritu protector de la tierra, y dejan peque\u00f1as espigas doradas en los linderos de los campos en su honor.", dex_draft: `Corstalk es la evolución de Mazorik, una criatura ágil que combina la firmeza del tallo con la astucia del depredador vegetal. Su cuerpo está formado por hojas entrelazadas que se afilan con el viento, y en su pecho brillan granos dorados que canalizan su energía vital.
Se mueve sigilosamente entre los campos, acechando como un guardián natural del suelo. Sus hojas-lanza pueden cortar incluso roca blanda, y su cuerpo flexible le permite esquivar ataques con elegancia.
Cuando corre, las vetas doradas de sus hojas se encienden, dejando un destello que parece la estela del sol sobre un mar de maíz.`, stats: { hp: 75, atk: 100, def: 80, spa: 50, spd: 70, spe: 95 }},
  {id: 120, name: "Talom", types: ["Roca", "Fantasma"], image: "Sprite/Talom.png", definition: "Pok\u00e9mon Aut\u00f3mata L\u00edtico", curiosidades: "nan", dex_draft: `Talom es un gólem creado por una civilización antigua especializada en la geometría sagrada y la animación ritual de la piedra. Su cuerpo está compuesto por bloques minerales encajados con precisión, unidos por un núcleo energético sellado en su interior. Carece de rasgos faciales visibles; su conciencia se manifiesta como dos luces que emergen desde la cavidad de su yelmo. Era utilizado para labores de construcción, custodia y transporte en ciudades ceremoniales, permaneciendo inerte durante siglos hasta ser activado.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 121, name: "Talurak", types: ["Roca", "Fantasma"], image: "Sprite/Talurak.png", definition: "Pok\u00e9mon Coloso Ancestral", curiosidades: "nan", dex_draft: `Talurak es la evolución de Talom tras absorber grandes cantidades de energía ritual y minerales refinados. Su estructura se vuelve más compleja y estable, reforzada por anillos pétreos y conductos dorados que distribuyen la fuerza desde su núcleo central. Fue diseñado como guardián perpetuo de templos, caminos sagrados y enclaves históricos. A diferencia de otros gólems, Talurak no obedece órdenes directas: actúa únicamente cuando percibe una alteración grave del equilibrio del territorio que protege.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 122, name: "Lapiantis", types: ["Agua", "Planta"], image: "Sprite/Lapiantis.png", definition: "Pokemon pantano", curiosidades: "Se cree que las plantas que crecen sobre su caparaz\u00f3n establecen un v\u00ednculo simbi\u00f3tico con \u00e9l: absorben su energ\u00eda vital a cambio de protegerlo del sol y los par\u00e1sitos.", dex_draft: `Lapiantis es el antepasado de Lapras, una criatura que habitaba los pantanos y lagunas templadas mucho antes de que su especie migrara a los mares helados.
Su caparazón estaba cubierto de musgo y flores silvestres que crecían gracias a los nutrientes que acumulaba en su piel húmeda. Se desplazaba lentamente entre los juncos, camuflándose con la vegetación y ofreciendo su espalda como refugio a pequeños Pokémon acuáticos.
En lugar de comunicarse mediante cánticos, Lapiantis emitía sonidos graves y burbujeantes que se confundían con el murmullo del agua, lo que lo convertía en un ser tan pacífico como enigmático.`, stats: { hp: 130, atk: 85, def: 75, spa: 90, spd: 95, spe: 60 }},
  {id: 130, name: "Ferrabuto", types: ["Acero", "Agua"], image: "Sprite/Ferrabuto.png", definition: "C\u00fapula Antigua", curiosidades: "nan", dex_draft: `Ferrabuto protegía su blando cuerpo con una cúpula de mineral pulido que se endurecía con los siglos. Vivía pegado al fondo marino, filtrando nutrientes y ocultándose de depredadores bajo la arena.
Cuando detecta vibraciones, retrae sus patas y se cierra por completo, volviéndose indistinguible de una roca.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 131, name: "Sideratops", types: ["Acero"], image: "Sprite/Sideratops.png", definition: "Pok\u00e9mon Arma", curiosidades: "nan", dex_draft: `La evolución de Ferrabuto que emergió cuando los mares se retiraron. Su caparazón se alargó en filosas cuchillas con las que cazaba y defendía su territorio.
Sus movimientos eran tan precisos que podía cortar la corriente marina a su paso.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 132, name: "Ammonyte", types: ["Tierra"], image: "Sprite/Ammonyte.png", definition: "Pok\u00e9mon Espiral", curiosidades: "nan", dex_draft: `Ammonyte vive semienterrado en los pantanos, usando sus tentáculos para remover el fango y buscar nutrientes. Su concha, dura y porosa, le permite flotar durante las crecidas del río sin hundirse.
A menudo se le ve girando lentamente sobre sí mismo, filtrando el barro para extraer materia orgánica.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 133, name: "Ammostar", types: ["Tierra"], image: "Sprite/Ammostar.png", definition: "Pok\u00e9mon Espiral", curiosidades: "nan", dex_draft: `La evolución de Ammonyte ha desarrollado una concha más resistente y cubierta de púas naturales que usa para intimidar a sus rivales.
En época de lluvias, patrulla los humedales con movimientos torpes pero firmes, dejando surcos en el lodo que sirven de refugio a otros Pokémon pequeños. Cuando se siente amenazado, se enrolla dentro de su concha y rueda, levantando una nube de barro que le sirve de camuflaje.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 134, name: "Aetherax", types: ["Volador"], image: "Sprite/Aetherax.png", definition: "Ave Primigenia", curiosidades: "nan", dex_draft: `Aetherax es considerado el antepasado directo de Aerodactyl, una criatura que dominó los cielos de Aionia antes de la fractura temporal.
A diferencia de su descendiente fosilizado, Aetherax posee un plumaje fino y oscuro que le permite regular la temperatura durante sus vuelos a gran altura.
Su estructura ósea es ligera pero resistente, y sus alas producen un silbido profundo al batir el aire, sonido que los antiguos habitantes interpretaban como el rugido del cielo.`, stats: { hp: 85, atk: 110, def: 70, spa: 65, spd: 65, spe: 120 }},
  {id: 147, name: "Noxal", types: ["Siniestro", "Fantasma"], image: "Sprite/Noxal.png", definition: "El F\u00e9nix del Crep\u00fasculo", curiosidades: "nan", dex_draft: `Cuando la última luz del día se apaga, Noxal abre sus alas. Dicen que nació del primer atardecer, cuando el fuego de Aerion necesitó un final para poder renacer. Es el guardián del reposo, la voz del silencio que sigue al paso del tiempo. Sus plumas absorben la luz y su vuelo deja un eco que se desvanece lentamente, como el último segundo de un reloj antes de detenerse.
En su pecho arde una geoda púrpura, el corazón de la noche, que late al ritmo del universo moribundo. Se dice que Noxal no destruye, sino que libera: apaga lo que sufre para devolverlo al vacío de donde vino. Su enfrentamiento con Aerion no fue por odio, sino por equilibrio; sin embargo, su conflicto incesante provocó que Kaironos perdiera el control. Cuando se cierne sobre el cielo, incluso las estrellas parecen inclinarse ante su vuelo, temiendo el momento en que todo vuelva a la oscuridad.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 148, name: "Helion", types: ["Fuego", "Hada"], image: "Sprite/Helion.png", definition: "El Horizonte del Amanecer", curiosidades: "nan", dex_draft: `Aerion nació del primer destello de luz que rompió la oscuridad del mundo. Representa el impulso vital, la chispa que hace avanzar el tiempo y enciende el deseo de creación. Su cuerpo irradia calor y serenidad, y sus pasos dejan flores que se marchitan al instante, símbolo del ciclo eterno del nacimiento y la pérdida.
Cuando extiende sus astas llameantes, el amanecer se alza incluso en noches sin sol. Los antiguos textos de Aionia cuentan que su voz podía acelerar el crecimiento de los bosques o hacer que las montañas se levantaran en un solo día. Sin embargo, su ansia de ver al mundo avanzar sin detenerse provocó desequilibrio en el flujo del tiempo. Su resplandor fue tan intenso que encendió la ira de Noxal y la desesperación de Kaironos, dando inicio al cataclismo temporal. En las leyendas, Aerion no es solo la luz del día: es el deseo eterno de seguir adelante, sin mirar atrás.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }},
  {id: 149, name: "Kaironos", types: ["Dragón", "Psiquico"], image: "Sprite/Kaironos.png", definition: "N\u00facleo del Colapso", curiosidades: "nan", dex_draft: `Hace diez mil años, Kaironos sintió el peso de cada instante que existía. Su mente percibía el pasado, el presente y el futuro al mismo tiempo, una visión infinita que ningún ser podía soportar. Se dice que su rugido no fue de furia, sino de desesperación, y que con él quebró la corriente del tiempo. En un solo segundo, arrastró al mundo de Aionia miles de años hacia adelante, dejando cicatrices que aún distorsionan la realidad.
Su cuerpo, formado por fragmentos suspendidos de engranajes y relojes, flota en un equilibrio imposible, como si se mantuviera unido por pura voluntad. Aunque muchos lo temen, Kaironos no busca destrucción: intenta restaurar el flujo que rompió. Los pocos que lo han visto afirman que cuando abre sus alas, el aire se detiene y los relojes dejan de marcar la hora, como si el universo contuviera la respiración ante el guardián del tiempo.`, stats: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 }}
];
